[dependencies]
frost-evm = { git = "https://github.com/Analog-labs/frost-evm.git", version = "0.1.0" }
log = "0.4.19"
rand = "0.8"
serde = { features = [ "derive" ], version = "1.0.171" }

[dev-dependencies]
env_logger = "0.10.0"
[package]
authors = [ "Dev <Dev@analog.one>" ]
edition = "2021"
homepage = "https://www.analog.one/"
license = "Apache-2.0"
name = "tesseract-tss"
repository = "https://github.com/Analog-Labs/tesseract/"
version = "0.0.1"
