[package]
name = "tss"
authors = [ "Dev <Dev@analog.one>" ]
edition = "2021"
homepage = "https://www.analog.one/"
license = "Apache-2.0"
repository = "https://github.com/Analog-Labs/tesseract/"
version = "0.0.1"

[dependencies]
anyhow = "1.0.75"
dirs = "5.0.1"
hex = "0.4"
frost-evm = { git = "https://github.com/analog-labs/frost-evm.git", version = "0.1.0", features = ["serde"] }
rand_core = { version = "0.6.4", features = ["getrandom"] }
serde = { version = "1.0.188", features = [ "derive" ] }
serde_json = "1.0.108"
time-primitives = { path = "../primitives" }
tracing = "0.1.37"

[dev-dependencies]
env_logger = "0.10.0"
