[package]
name = "pallet-timegraph"
authors = [ "Analog Devs <https://github.com/analog-labs>" ]
description = "A pallet for tokenomics of timegraph."
edition = "2021"
homepage = "https://analog.one"
license = "Unlicense"
publish = false
repository = "https://github.com/Analog-Labs/testnet"
version = "0.0.1"
[dependencies]
codec = { package = "parity-scale-codec", version = "3.6", default-features = false, features = [ "max-encoded-len" ] }
frame-benchmarking = {  git = "https://github.com/Analog-Labs/polkadot-sdk.git", tag = "v1.6.0-tracing", default-features = false, optional = true }
frame-support = { git = "https://github.com/Analog-Labs/polkadot-sdk.git", tag = "v1.6.0-tracing", default-features = false}
frame-system = { git = "https://github.com/Analog-Labs/polkadot-sdk.git", tag = "v1.6.0-tracing", default-features = false}
scale-info = { version = "2.9.0", default-features = false, features = [ "derive" ] }

[dev-dependencies]
pallet-balances = { git = "https://github.com/Analog-Labs/polkadot-sdk.git", tag = "v1.6.0-tracing" }
sp-core = { git = "https://github.com/Analog-Labs/polkadot-sdk.git", tag = "v1.6.0-tracing" }
sp-io = { git = "https://github.com/Analog-Labs/polkadot-sdk.git", tag = "v1.6.0-tracing" }
sp-runtime = { git = "https://github.com/Analog-Labs/polkadot-sdk.git", tag = "v1.6.0-tracing" }

[features]
default = [ "std" ]
std = [
	"codec/std",
	"frame-benchmarking?/std",
	"frame-support/std",
	"frame-system/std",
	"scale-info/std",
]

runtime-benchmarks = [ "frame-benchmarking/runtime-benchmarks", "pallet-balances/runtime-benchmarks" ]
try-runtime = [ "frame-support/try-runtime" ]
