[package]
name = "time-primitives"
edition = "2021"
version = "0.1.0"

[dependencies]
alloy-primitives = { version = "0.6.4", default-features = false }
alloy-sol-types = { version = "0.6.4", default-features = false }
anyhow = { version = "1.0", default-features = false }
async-trait = "0.1.73"
codec = { package = "parity-scale-codec", version = "3.6.12", default-features = false }
frame-support = { git = "https://github.com/analog-labs/polkadot-sdk", tag = "v1.13.0-patched", default-features = false }
frame-system = { git = "https://github.com/analog-labs/polkadot-sdk", tag = "v1.13.0-patched", default-features = false }
futures = { version = "0.3.28", optional = true }
log = "0.4.20"
scale-info = { version = "2.9.0", default-features = false, features = [ "derive" ] }
serde = { version = "1.0", default-features = false, features = [ "derive", "alloc" ] }
sha3 = { version = "0.10", default-features = false }
sp-api = { git = "https://github.com/analog-labs/polkadot-sdk", tag = "v1.13.0-patched", default-features = false }
sp-application-crypto = { git = "https://github.com/analog-labs/polkadot-sdk", tag = "v1.13.0-patched", default-features = false }
sp-core = { git = "https://github.com/analog-labs/polkadot-sdk", tag = "v1.13.0-patched", default-features = false }
sp-io = { git = "https://github.com/analog-labs/polkadot-sdk", tag = "v1.13.0-patched", default-features = false }
sp-runtime = { git = "https://github.com/analog-labs/polkadot-sdk", tag = "v1.13.0-patched", default-features = false }
sp-std = { git = "https://github.com/analog-labs/polkadot-sdk", tag = "v1.13.0-patched", default-features = false }

[features]
default = ["std"]
std = ["codec/std", "frame-support/std", "frame-system/std", "futures", "scale-info/std", "sp-api/std", "sp-application-crypto/std", "sp-core/std", "sp-runtime/std", "sp-std/std"]

[dev-dependencies]
hex = "0.4.3"
