[dependencies]
anyhow = { default-features = false, version = "1.0" }
codec = { default-features = false, package = "parity-scale-codec", version = "3.6.3" }
frame-system = { branch = "polkadot-v1.0.0", default-features = false, git = "https://github.com/paritytech/substrate.git" }
futures = { optional = true, version = "0.3.28" }
log = "0.4.19"
scale-info = { default-features = false, features = [ "derive" ], version = "2.9.0" }
serde = { default-features = false, features = [ "derive" ], version = "1.0" }
sp-api = { branch = "polkadot-v1.0.0", default-features = false, git = "https://github.com/paritytech/substrate.git" }
sp-application-crypto = { branch = "polkadot-v1.0.0", default-features = false, git = "https://github.com/paritytech/substrate.git" }
sp-core = { branch = "polkadot-v1.0.0", default-features = false, git = "https://github.com/paritytech/substrate.git" }
sp-runtime = { branch = "polkadot-v1.0.0", default-features = false, git = "https://github.com/paritytech/substrate.git" }
sp-std = { branch = "polkadot-v1.0.0", default-features = false, git = "https://github.com/paritytech/substrate.git" }

[features]
default = [ "std" ]
std = [ "futures", "codec/std", "frame-system/std", "scale-info/std", "sp-api/std", "sp-application-crypto/std", "sp-core/std", "sp-runtime/std", "sp-std/std" ]
[package]
edition = "2021"
name = "time-primitives"
version = "0.1.0"
