[package]
name = "tesseract-tss"
version = "0.0.1"
authors = ["Dev <Dev@analog.one>"]
edition = "2021"
license = "Apache-2.0"
homepage = "https://www.analog.one/"
repository = "https://github.com/Analog-Labs/tesseract/"

[dependencies]
blake3 = "1.3.3"
frost-evm = { version = "0.1.0", git = "https://github.com/Analog-labs/frost-evm.git"}
log = "0.4.17"
rand = "0.8"
serde = { version = "1.0.160", features = ["derive"] }

[dev-dependencies]
env_logger = "0.10.0"
