[package]
name = "pallet-tasks"
description = "A pallet for storing task(s) schedule info."
publish = false
readme = "pallets/tasks/README.md"

version.workspace = true
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
log.workspace = true
scale-codec = { workspace = true, features = [ "max-encoded-len" ] }
scale-info.workspace = true

#polkadot-sdk = { workspace = true, features = [ "frame-support", "frame-system", "pallet_balances", "sp-core", "sp-runtime", "sp-std" ] }

frame-support = { git = "https://github.com/analog-labs/polkadot-sdk", tag = "v1.15.1-anlog0", default-features = false }
frame-system = { git = "https://github.com/analog-labs/polkadot-sdk", tag = "v1.15.1-anlog0", default-features = false }
pallet-balances = { git = "https://github.com/analog-labs/polkadot-sdk", tag = "v1.15.1-anlog0", default-features = false }
pallet-treasury = { git = "https://github.com/analog-labs/polkadot-sdk", tag = "v1.13.0-patched2", default-features = false }
sp-core = { git = "https://github.com/analog-labs/polkadot-sdk", tag = "v1.15.1-anlog0", default-features = false }
sp-runtime = { git = "https://github.com/analog-labs/polkadot-sdk", tag = "v1.15.1-anlog0", default-features = false }
sp-std = { git = "https://github.com/analog-labs/polkadot-sdk", tag = "v1.15.1-anlog0", default-features = false }

frame-benchmarking = { git = "https://github.com/analog-labs/polkadot-sdk", tag = "v1.15.1-anlog0", default-features = false, optional = true }

schnorr-evm = { version = "0.1.0", default-features = false }

pallet-elections.workspace = true
pallet-members.workspace = true
pallet-shards.workspace = true
time-primitives.workspace = true

simple-mermaid.workspace = true

[dev-dependencies]
#polkadot-sdk = { workspace = true, features = [ "sp-io" ] }

sp-io = { git = "https://github.com/analog-labs/polkadot-sdk", tag = "v1.15.1-anlog0", default-features = false }

[features]
default = [ "std" ]
std = [
	"log/std",
	"scale-codec/std",
	"scale-info/std",

	"polkadot-sdk/std",

	"schnorr-evm/std",

	"pallet-elections/std",
	"pallet-members/std",
	"pallet-shards/std",
	"time-primitives/std",
]
runtime-benchmarks = [
	"polkadot-sdk/runtime-benchmarks",
	"polkadot-sdk/frame-benchmarking",

	"pallet-elections/runtime-benchmarks",
	"pallet-members/runtime-benchmarks",
	"pallet-shards/runtime-benchmarks",
]
try-runtime = [
	"polkadot-sdk/try-runtime",

	"pallet-elections/try-runtime",
	"pallet-members/try-runtime",
	"pallet-shards/try-runtime",
]
