[package]
name = "pallet-tasks"
description = "A pallet for storing task(s) schedule info."
publish = false
readme = "pallets/tasks/README.md"

version.workspace = true
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
log.workspace = true
scale-codec = { workspace = true, features = [ "max-encoded-len" ] }
scale-info.workspace = true

polkadot-sdk = { workspace = true, features = [ "frame-support", "frame-system", "pallet-balances", "pallet-treasury", "sp-core", "sp-runtime", "sp-std" ] }

pallet-elections.workspace = true
pallet-networks.workspace = true
pallet-members.workspace = true
pallet-shards.workspace = true
time-primitives.workspace = true

simple-mermaid.workspace = true

[dev-dependencies]
polkadot-sdk = { workspace = true, features = [ "sp-io" ] }

[features]
default = [ "std" ]
std = [
	"log/std",
	"scale-codec/std",
	"scale-info/std",

	"polkadot-sdk/std",

	"pallet-elections/std",
	"pallet-members/std",
	"pallet-networks/std",
	"pallet-shards/std",
	"time-primitives/std",
]
runtime-benchmarks = [
	"polkadot-sdk/runtime-benchmarks",
	"polkadot-sdk/frame-benchmarking",

	"pallet-elections/runtime-benchmarks",
	"pallet-members/runtime-benchmarks",
	"pallet-shards/runtime-benchmarks",
]
try-runtime = [
	"polkadot-sdk/try-runtime",

	"pallet-elections/try-runtime",
	"pallet-members/try-runtime",
	"pallet-shards/try-runtime",
]
