[dependencies]
codec = { default-features = false, features = [ "max-encoded-len" ], package = "parity-scale-codec", version = "3.6.3" }
frame-benchmarking = { branch = "polkadot-v1.0.0", default-features = false, git = "https://github.com/paritytech/substrate.git", optional = true }
frame-support = { branch = "polkadot-v1.0.0", default-features = false, git = "https://github.com/paritytech/substrate" }
frame-system = { branch = "polkadot-v1.0.0", default-features = false, git = "https://github.com/paritytech/substrate" }
log = { default-features = false, version = "0.4.19" }
scale-info = { default-features = false, features = [ "derive" ], version = "2.9.0" }
sp-runtime = { branch = "polkadot-v1.0.0", default-features = false, git = "https://github.com/paritytech/substrate" }
sp-std = { branch = "polkadot-v1.0.0", default-features = false, git = "https://github.com/paritytech/substrate.git" }
time-primitives = { default-features = false, path = "../../primitives" }

[dev-dependencies]
pallet-balances = { branch = "polkadot-v1.0.0", git = "https://github.com/paritytech/substrate.git", version = "4.0.0-dev" }
sp-core = { branch = "polkadot-v1.0.0", default-features = false, git = "https://github.com/paritytech/substrate.git" }
sp-io = { branch = "polkadot-v1.0.0", default-features = false, git = "https://github.com/paritytech/substrate.git" }

[features]
default = [ "std" ]
std = [
	"codec/std",
	"frame-benchmarking?/std",
	"frame-support/std",
	"frame-system/std",
	"scale-info/std",
	"sp-runtime/std",
	"sp-std/std",
	"time-primitives/std",
]

runtime-benchmarks = [ "frame-benchmarking/runtime-benchmarks" ]
try-runtime = [ "frame-support/try-runtime" ]
[package]
authors = [ "Analog Devs <https://github.com/analog-labs>" ]
description = "A pallet for storing task(s) schedule info."
edition = "2021"
homepage = "https://analog.one"
license = "Unlicense"
name = "pallet-tasks"
publish = false
repository = "https://github.com/Analog-Labs/testnet"
version = "0.0.1"
