[workspace]
members = [
    "node",
    "pallets/tesseract-sig-storage",
    "pallets/onchain-task",
    "pallets/authorship",
    "runtime",
    "workers/time-worker",
    "primitives/time-primitives",
    "tesseract/tss",
    "tesseract/accounts",
    "tesseract/events"
]
[profile.release]
panic = "unwind"
   
