[workspace]
members = [
    "node",
    "pallets/tesseract-sig-storage",
    "pallets/onchain-task",
    "runtime",
    "workers/time-worker",
    "primitives/time-primitives"
]
[profile.release]
panic = "unwind"
   
