[workspace]
members = [
    "node",
    "pallets/pallet-timegraph",
    "pallets/task-schedule",
    "pallets/task-schedule/task-schedule-bench",
    "pallets/tesseract-sig-storage",
    "pallets/vesting",
    "primitives/time-primitives",
    "runtime",
    "runtime/common",
    "tss",
    "workers/task-executor",
    "workers/timechain-integration",
    "workers/time-worker",
]
resolver = "2"

[profile.release]
panic = "unwind"
strip = true
opt-level = "z"

[profile.release-codecov]
inherits = "release"
strip = false
