[workspace]
members = [
	"chronicle",
	"node",
	"pallets/elections",
	"pallets/members",
	"pallets/shards",
	"pallets/tasks",
	"primitives",
	"runtime",
	"runtime/common",
	"tss",
	"tester"
]
resolver = "2"

[profile.release]
opt-level = "z"
panic = "unwind"
strip = true

[profile.release-codecov]
inherits = "release"
strip = false
