[workspace]
members = [
    "node",
    "pallets/tesseract-sig-storage",
    "pallets/pallet-proxy",
    "runtime",
    "workers/time-worker",
    "workers/time-worker/rpc",
    "workers/database",
    "primitives/time-primitives",
    "primitives/storage-primitives",
    "tesseract/tss",
    "tesseract/accounts",
    "tesseract/events",
    "pallets/task-metadata",
    "pallets/task-schedule",
    "pallets/task-metadata/task-meta-bench",
]

[profile.release]
panic = "unwind"
strip = true
opt-level = "z"

[profile.release-codecov]
inherits = "release"
strip = false
