[workspace]
members = [
    "node",
    "pallets/ocw",
    "pallets/shards",
    "pallets/tasks",
    "pallets/vesting",
    "primitives/time-primitives",
    "runtime",
    "runtime/common",
    "tss",
    "workers/task-executor",
    "workers/timechain-integration",
    "workers/time-worker",
]
resolver = "2"

[profile.release]
panic = "unwind"
strip = true
opt-level = "z"

[profile.release-codecov]
inherits = "release"
strip = false
