[profile.release]
opt-level = "z"
panic = "unwind"
strip = true

[profile.release-codecov]
inherits = "release"
strip = false
[workspace]
members = [
	"node",
	"pallets/ocw",
	"pallets/shards",
	"pallets/tasks",
	"pallets/vesting",
	"primitives",
	"runtime",
	"runtime/common",
	"tss",
	"workers/task-executor",
	"workers/timechain-integration",
	"workers/time-worker",
]
resolver = "2"
