[workspace]
members = [
    "node",
    "pallets/tesseract-sig-storage",
    "pallets/pallet-proxy",
    "runtime",
    "workers/payable-task-executor",
    "workers/task-executor",
    "workers/time-worker",
    "workers/time-worker/rpc",
    "workers/database",
    "primitives/time-primitives",
    "tss",
    "pallets/task-metadata",
    "pallets/task-schedule",
    "pallets/task-metadata/task-meta-bench",
    "pallets/task-schedule/task-schedule-bench",
]
resolver = "2"

[profile.release]
panic = "unwind"
strip = true
opt-level = "z"

[profile.release-codecov]
inherits = "release"
strip = false
