[workspace]
members = [
    "node",
    "pallets/pallet-proxy",
    "pallets/task-metadata",
    "pallets/task-metadata/task-meta-bench",
    "pallets/task-schedule",
    "pallets/task-schedule/task-schedule-bench",
    "pallets/tesseract-sig-storage",
    "pallets/vesting",
    "primitives/time-primitives",
    "runtime",
    "runtime/common",
    "tss",
    "workers/database",
    "workers/database/migration",
    "workers/event-worker",
    "workers/payable-task-executor",
    "workers/task-executor",
    "workers/timechain-integration",
    "workers/time-worker",
    "workers/time-worker/rpc",
]
resolver = "2"

[profile.release]
panic = "unwind"
strip = true
opt-level = "z"

[profile.release-codecov]
inherits = "release"
strip = false

[patch.crates-io]
rosetta-client = { git = "https://github.com/analog-labs/chain-connectors" }
rosetta-docker = { git = "https://github.com/analog-labs/chain-connectors" }