services:
  validator:
    image: 'analoglabs/timechain-node-develop'
    command:
    - '--chain=dev'
    - '--base-path=/data'
    - '--rpc-cors=all'
    - '--unsafe-rpc-external'
    - '--rpc-methods=unsafe'
    - '--prometheus-external'
    - '--prometheus-port=9090'
    - '--alice'
    - '--validator'
    - '--force-authoring'
    - '--node-key=0000000000000000000000000000000000000000000000000000000000000001'
    - '-ltxpool=trace,basic_authorship=trace,runtime=trace'
    ports:
      - 9944:9944

  gmp-grpc-0:
    image: 'analoglabs/gmp-grpc-develop'
    command:
    - '--network-id=0'
    - '--port=3000'
    - '--db=/etc/db'
    environment:
      RUST_LOG: 'gmp_grpc=debug,gmp_rust=debug'
      RUST_BACKTRACE: 1

  chronicle-0:
    image: 'analoglabs/chronicle-develop'
    command:
    - '--timechain-keyfile=/etc/timechain_keyfile'
    - '--network-keyfile=/etc/network_keyfile'
    - '--target-keyfile=/etc/target_keyfile'
    - '--tss-keyshare-cache=/etc/tss'
    - '--timechain-url=ws://validator:9944'
    - '--target-url=http://gmp-grpc-0:3000'
    - '--timechain-min-balance=1000000000000'
    - '--target-min-balance=10000'
    - '--network-id=0'
    - '--backend=grpc'
    environment:
      RUST_LOG: 'tc_subxt=debug,chronicle=debug,tss=debug'
      RUST_BACKTRACE: 1
    ports:
      - "8080:8080"

  gmp-grpc-1:
    image: 'analoglabs/gmp-grpc-develop'
    command:
    - '--network-id=1'
    - '--port=3000'
    - '--db=/etc/db'
    environment:
      RUST_LOG: 'gmp_grpc=debug,gmp_rust=debug'
      RUST_BACKTRACE: 1

  chronicle-1:
    image: 'analoglabs/chronicle-develop'
    command:
    - '--timechain-keyfile=/etc/timechain_keyfile'
    - '--network-keyfile=/etc/network_keyfile'
    - '--target-keyfile=/etc/target_keyfile'
    - '--tss-keyshare-cache=/etc/tss'
    - '--timechain-url=ws://validator:9944'
    - '--target-url=http://gmp-grpc-1:3000'
    - '--timechain-min-balance=1000000000000'
    - '--target-min-balance=10000'
    - '--network-id=1'
    - '--backend=grpc'
    environment:
      RUST_LOG: 'tc_subxt=debug,chronicle=debug,tss=debug'
      RUST_BACKTRACE: 1
    ports:
      - "8081:8080"

  chronicle-2:
    image: 'analoglabs/chronicle-develop'
    command:
    - '--timechain-keyfile=/etc/timechain_keyfile'
    - '--network-keyfile=/etc/network_keyfile'
    - '--target-keyfile=/etc/target_keyfile'
    - '--tss-keyshare-cache=/etc/tss'
    - '--timechain-url=ws://validator:9944'
    - '--target-url=ws://ethereum:8545'
    - '--timechain-min-balance=1000000000000'
    - '--target-min-balance=10000'
    - '--network-id=3'
    - '--backend=evm'
    # this contract is created as destination contract when we run the smoke-test first time
    - '--cctp-sender=0x981f8b5cd4de6b1a925854b63be9411b48b60bf2'
    # for circle testnet attestations
    - '--cctp-attestation="https://iris-api-sandbox.circle.com/v1/attestation/"'
    environment:
      RUST_LOG: 'tc_subxt=debug,chronicle=debug,tss=debug,gmp_evm=info'
      RUST_BACKTRACE: 1
    ports:
      - "8082:8080"
    profiles:
    - ethereum

  ethereum:
    image: 'ethereum/client-go:v1.14.11'
    command:
    - '--dev'
    - '--dev.gaslimit=30000000'
    - '--ipcdisable'
    - '--dev.period=2'
    - '--rpc.txfeecap=0'
    - '--rpc.allow-unprotected-txs=true'
    - '--http'
    - '--http.addr=0.0.0.0'
    - '--http.port=8545'
    - '--http.vhosts=*'
    - '--http.corsdomain=*'
    - '--http.api=eth,debug,admin,txpool,web3,net'
    - '--ws'
    - '--ws.addr=0.0.0.0'
    - '--ws.port=8545'
    - '--ws.origins=*'
    - '--ws.api=eth,debug,admin,txpool,web3,net'
    - '--verbosity=4'
    profiles:
    - ethereum
    ports:
    - 8545:8545

  tc-cli:
    image: 'analoglabs/tc-cli-develop'
    environment:
      RUST_LOG: 'tc_subxt=debug,tc_cli=debug,gmp_evm=info'
      RUST_BACKTRACE: 1
    volumes:
    - './config/envs/local/local-evm.yaml:/etc/config.yaml:ro'
    - './config/envs/local/prices.csv:/etc/prices.csv'
    - './analog-gmp/out:/etc/contracts:ro'
    - './gmp/evm/factory/additional_config.json:/etc/deployer/additional_config.json:ro'
    env_file:
    - './config/envs/local/.env'
    profiles:
    - never
