# Setup for Prometheus, Promtail, Loki and grafana

version: '3.9'

services:
  prometheus:
    image: prom/prometheus:v2.36.2
    volumes:
    - ./config/prometheus/:/etc/prometheus/
    - prometheus-docker-sd:/prometheus-docker-sd:ro
    command:
    - '--config.file=/etc/prometheus/prometheus.yaml'
    - '--storage.tsdb.path=/prometheus'
    - '--web.console.libraries=/usr/share/prometheus/console_libraries'
    - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
    - 9090:9090
    restart: always

  prometheus-docker-sd:
    image: "stucky/prometheus-docker-sd:latest"
    restart: unless-stopped
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - prometheus-docker-sd:/prometheus-docker-sd:rw

  loki:
    image: grafana/loki:2.9.0
    ports:
    - 3100:3100
    command: -config.file=/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:2.9.0
    volumes:
    - ./config/promtail/promtail.yaml:/etc/promtail/docker-config.yaml
    - /var/lib/docker/containers:/var/lib/docker/containers:ro
    - /var/run/docker.sock:/var/run/docker.sock
    command: -config.file=/etc/promtail/docker-config.yaml

  grafana:
    image: grafana/grafana
    ports:
    - 3000:3000
    volumes:
    - ./config/grafana/:/etc/grafana/provisioning/
    environment:
    - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
    - prometheus
    - loki
    restart: always

volumes:
  prometheus-docker-sd:
