services:
  validator:
    image: 'analoglabs/timechain-node-develop'
    command:
    - '--chain=dev'
    - '--base-path=/data'
    - '--rpc-cors=all'
    - '--unsafe-rpc-external'
    - '--rpc-methods=unsafe'
    - '--prometheus-external'
    - '--prometheus-port=9090'
    - '--alice'
    - '--validator'
    - '--force-authoring'
    - '--node-key=0000000000000000000000000000000000000000000000000000000000000001'
    - '-ltxpool=trace,basic_authorship=trace,runtime=trace'
    ports:
      - 9944:9944

  chain-0-grpc:
    image: 'analoglabs/gmp-grpc-develop'
    command:
    - '--network-id=0'
    - '--port=3000'
    - '--db=/etc/db'
    environment:
      RUST_LOG: 'gmp_grpc=debug,gmp_rust=debug'
      RUST_BACKTRACE: 1
    profiles:
    - grpc

  chronicle-0-grpc:
    image: 'analoglabs/chronicle-develop'
    command:
    - '--timechain-keyfile=/etc/timechain_keyfile'
    - '--network-keyfile=/etc/network_keyfile'
    - '--target-keyfile=/etc/target_keyfile'
    - '--tss-keyshare-cache=/etc/tss'
    - '--timechain-url=ws://validator:9944'
    - '--target-url=http://chain-0-grpc:3000'
    - '--network-id=0'
    - '--backend=grpc'
    environment:
      RUST_LOG: 'tc_subxt=debug,chronicle=debug,tss=debug'
      RUST_BACKTRACE: 1
    profiles:
    - grpc

  chain-1-grpc:
    image: 'analoglabs/gmp-grpc-develop'
    command:
    - '--network-id=1'
    - '--port=3000'
    - '--db=/etc/db'
    environment:
      RUST_LOG: 'gmp_grpc=debug,gmp_rust=debug'
      RUST_BACKTRACE: 1
    profiles:
    - grpc

  chronicle-1-grpc:
    image: 'analoglabs/chronicle-develop'
    command:
    - '--timechain-keyfile=/etc/timechain_keyfile'
    - '--network-keyfile=/etc/network_keyfile'
    - '--target-keyfile=/etc/target_keyfile'
    - '--tss-keyshare-cache=/etc/tss'
    - '--timechain-url=ws://validator:9944'
    - '--target-url=http://chain-1-grpc:3000'
    - '--network-id=1'
    - '--backend=grpc'
    environment:
      RUST_LOG: 'tc_subxt=debug,chronicle=debug,tss=debug'
      RUST_BACKTRACE: 1
    profiles:
    - grpc

  chain-2-evm:
    image: 'ethereum/client-go:v1.14.11'
    command:
    - '--dev'
    - '--dev.gaslimit=30000000'
    - '--ipcdisable'
    - '--dev.period=2'
    - '--rpc.txfeecap=0'
    - '--rpc.allow-unprotected-txs=true'
    - '--http'
    - '--http.addr=0.0.0.0'
    - '--http.port=8545'
    - '--http.vhosts=*'
    - '--http.corsdomain=*'
    - '--http.api=eth,debug,admin,txpool,web3,net'
    - '--ws'
    - '--ws.addr=0.0.0.0'
    - '--ws.port=8545'
    - '--ws.origins=*'
    - '--ws.api=eth,debug,admin,txpool,web3,net'
    - '--verbosity=4'
    profiles:
    - evm

  chronicle-2-evm:
    image: 'analoglabs/chronicle-develop'
    command:
    - '--timechain-keyfile=/etc/timechain_keyfile'
    - '--network-keyfile=/etc/network_keyfile'
    - '--target-keyfile=/etc/target_keyfile'
    - '--tss-keyshare-cache=/etc/tss'
    - '--timechain-url=ws://validator:9944'
    - '--target-url=ws://chain-2-evm:8545'
    - '--network-id=2'
    - '--backend=evm'
    environment:
      RUST_LOG: 'tc_subxt=debug,chronicle=debug,tss=debug,gmp_evm=info'
      RUST_BACKTRACE: 1
    profiles:
    - evm

  chain-3-evm:
    image: 'ethereum/client-go:v1.14.11'
    command:
    - '--dev'
    - '--dev.gaslimit=30000000'
    - '--ipcdisable'
    - '--dev.period=2'
    - '--rpc.txfeecap=0'
    - '--rpc.allow-unprotected-txs=true'
    - '--http'
    - '--http.addr=0.0.0.0'
    - '--http.port=8545'
    - '--http.vhosts=*'
    - '--http.corsdomain=*'
    - '--http.api=eth,debug,admin,txpool,web3,net'
    - '--ws'
    - '--ws.addr=0.0.0.0'
    - '--ws.port=8545'
    - '--ws.origins=*'
    - '--ws.api=eth,debug,admin,txpool,web3,net'
    - '--verbosity=4'
    profiles:
    - evm

  chronicle-3-evm:
    image: 'analoglabs/chronicle-develop'
    command:
    - '--timechain-keyfile=/etc/timechain_keyfile'
    - '--network-keyfile=/etc/network_keyfile'
    - '--target-keyfile=/etc/target_keyfile'
    - '--tss-keyshare-cache=/etc/tss'
    - '--timechain-url=ws://validator:9944'
    - '--target-url=ws://chain-3-evm:8545'
    - '--network-id=3'
    - '--backend=evm'
    environment:
      RUST_LOG: 'tc_subxt=debug,chronicle=debug,tss=debug,gmp_evm=info'
      RUST_BACKTRACE: 1
    profiles:
    - evm

  tc-cli:
    image: 'analoglabs/tc-cli-develop'
    environment:
      RUST_BACKTRACE: 1
    profiles:
    - never
