services:
  validator:
    image: 'analoglabs/timenode-development'
    command:
    - '--chain=dev'
    - '--base-path=/data'
    - '--rpc-cors=all'
    - '--unsafe-rpc-external'
    - '--rpc-methods=unsafe'
    - '--prometheus-external'
    - '--prometheus-port=9090'
    - '--alice'
    - '--validator'
    - '--force-authoring'
    - '--node-key=0000000000000000000000000000000000000000000000000000000000000001'
    labels:
      prometheus-scrape.enabled: 'true'
    ports:
      - 9944:9944

  chronicle-0:
    image: 'analoglabs/chronicle-development'
    environment:
      RUST_LOG: 'tc_subxt=debug,chronicle=debug,tss=debug'
      RUST_BACKTRACE: 1
    restart: 'always'
    command:
    - '--timechain-metadata=development'
    - '--timechain-url=ws://validator:9944'
    - '--timechain-keyfile=/etc/timechain_keyfile'
    - '--tss-keyshare-cache=/etc/tss'
    - '--target-url=/etc/target'
    - '--target-keyfile=/etc/target_keyfile'
    - '--network-id=0'

  tc-cli:
    image: 'analoglabs/tc-cli-development'
    profiles:
    - never
    environment:
      RUST_LOG: 'tc_subxt=debug,tester=debug'
      RUST_BACKTRACE: 1
    volumes:
    - './config/wallets/target_admin:/etc/target_admin:ro'
    - './config/wallets/timechain_admin:/etc/timechain_admin:ro'
    - './analog-gmp/out:/etc/contracts:ro'
