version: '3.9'
volumes:
  bootnode-volume:
  validator1-volume:
  validator2-volume:
  validator3-volume:
  validator4-volume:
  validator5-volume:
  validator6-volume:
  validator7-volume:
  validator8-volume:
  ethereum-volume:
  astar-volume:
  pgsql-dbx-volume:
services:
  bootnode:
    image: 'analoglabs/timechain-node'
    command:
    - '--validator'
    - '--base-path=/data'
    - '--chain=dev'
    - '--rpc-cors=all'
    - '--unsafe-rpc-external'
    - '--rpc-methods=unsafe'
    - '--offchain-worker=Always'
    - '--connector-url=ws://ethereum:8545'
    - '--connector-blockchain=ethereum'
    - '--connector-network=dev'
    - '--network=ethereum'
    - '--keyfile=/etc/eth_keyfile1'
    - '--alice'
    - '--node-key=0000000000000000000000000000000000000000000000000000000000000001'
    environment:
      RUST_LOG: 'tesseract_tss=debug,time-worker=debug,task-executor=debug'
    depends_on:
    - ethereum-connector
    volumes:
    - './dummy_wallets/eth_keyfile1:/etc/eth_keyfile1'
    - 'bootnode-volume:/data'
    ports:
    - '9943:9944'
    extra_hosts:
    - "host.docker.internal:host-gateway"
    profiles:
    - astar
    - ethereum

  validator1:
    image: 'analoglabs/timechain-node'
    command:
    - '--validator'
    - '--base-path=/data'
    - '--chain=dev'
    - '--rpc-cors=all'
    - '--unsafe-rpc-external'
    - '--rpc-methods=unsafe'
    - '--offchain-worker=Always'
    - '--connector-url=ws://ethereum:8545'
    - '--connector-blockchain=ethereum'
    - '--connector-network=dev'
    - '--network=ethereum'
    - '--keyfile=/etc/eth_keyfile2'
    - '--bob'
    - '--node-key=0000000000000000000000000000000000000000000000000000000000000002'
    - '--bootnodes=/dns4/bootnode/tcp/30333/p2p/12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp'
    environment:
      RUST_LOG: 'tesseract_tss=debug,time-worker=debug,task-executor=debug'
    depends_on:
    - bootnode
    - ethereum-connector
    volumes:
    - './dummy_wallets/eth_keyfile2:/etc/eth_keyfile2'
    - 'validator1-volume:/data'
    ports:
    - '9945:9944'
    extra_hosts:
    - "host.docker.internal:host-gateway"
    profiles:
    - astar
    - ethereum

  validator2:
    image: 'analoglabs/timechain-node'
    command:
    - '--validator'
    - '--base-path=/data'
    - '--chain=dev'
    - '--rpc-cors=all'
    - '--unsafe-rpc-external'
    - '--rpc-methods=unsafe'
    - '--offchain-worker=Always'
    - '--connector-url=ws://ethereum:8545'
    - '--connector-blockchain=ethereum'
    - '--connector-network=dev'
    - '--network=ethereum'
    - '--keyfile=/etc/eth_keyfile3'
    - '--charlie'
    - '--node-key=0000000000000000000000000000000000000000000000000000000000000003'
    - '--bootnodes=/dns4/bootnode/tcp/30333/p2p/12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp'
    environment:
      RUST_LOG: 'tesseract_tss=debug,time-worker=debug'
    depends_on:
    - bootnode
    - ethereum-connector
    volumes:
    - './dummy_wallets/eth_keyfile3:/etc/eth_keyfile3'
    - 'validator2-volume:/data'
    ports:
    - '9947:9944'
    extra_hosts:
    - "host.docker.internal:host-gateway"
    profiles:
    - astar
    - ethereum

  validator3:
    image: 'analoglabs/timechain-node'
    command:
    - '--validator'
    - '--base-path=/data'
    - '--chain=dev'
    - '--rpc-cors=all'
    - '--unsafe-rpc-external'
    - '--rpc-methods=unsafe'
    - '--offchain-worker=Always'
    - '--connector-url=ws://astar:9944'
    - '--connector-blockchain=astar'
    - '--connector-network=dev'
    - '--network=astar'
    - '--keyfile=/etc/astar_keyfile1'
    - '--dave'
    - '--node-key=0000000000000000000000000000000000000000000000000000000000000004'
    - '--bootnodes=/dns4/bootnode/tcp/30333/p2p/12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp'
    environment:
      RUST_LOG: 'tesseract_tss=debug,time-worker=debug'
    depends_on:
    - bootnode
    - astar-connector
    volumes:
    - './dummy_wallets/astar_keyfile1:/etc/astar_keyfile1'
    - 'validator3-volume:/data'
    ports:
    - '9949:9944'
    extra_hosts:
    - "host.docker.internal:host-gateway"
    profiles:
    - astar

  validator4:
    image: 'analoglabs/timechain-node'
    command:
    - '--validator'
    - '--base-path=/data'
    - '--chain=dev'
    - '--rpc-cors=all'
    - '--unsafe-rpc-external'
    - '--rpc-methods=unsafe'
    - '--offchain-worker=Always'
    - '--connector-url=ws://astar:9944'
    - '--connector-blockchain=astar'
    - '--connector-network=dev'
    - '--network=astar'
    - '--keyfile=/etc/astar_keyfile2'
    - '--eve'
    - '--node-key=0000000000000000000000000000000000000000000000000000000000000005'
    - '--bootnodes=/dns4/bootnode/tcp/30333/p2p/12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp'
    environment:
      RUST_LOG: 'tesseract_tss=debug,time-worker=debug'
    depends_on:
    - bootnode
    - astar-connector
    volumes:
    - './dummy_wallets/astar_keyfile2:/etc/astar_keyfile2'
    - 'validator4-volume:/data'
    ports:
    - '9951:9944'
    extra_hosts:
    - "host.docker.internal:host-gateway"
    profiles:
    - astar

  validator5:
    image: 'analoglabs/timechain-node'
    command:
    - '--validator'
    - '--base-path=/data'
    - '--chain=dev'
    - '--rpc-cors=all'
    - '--unsafe-rpc-external'
    - '--rpc-methods=unsafe'
    - '--offchain-worker=Always'
    - '--connector-url=ws://astar:9944'
    - '--connector-blockchain=astar'
    - '--connector-network=dev'
    - '--network=astar'
    - '--keyfile=/etc/astar_keyfile3'
    - '--ferdie'
    - '--node-key=0000000000000000000000000000000000000000000000000000000000000006'
    - '--bootnodes=/dns4/bootnode/tcp/30333/p2p/12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp'
    environment:
      RUST_LOG: 'tesseract_tss=debug,time-worker=debug'
    depends_on:
    - bootnode
    - astar-connector
    volumes:
    - './dummy_wallets/astar_keyfile3:/etc/astar_keyfile3'
    - 'validator5-volume:/data'
    ports:
    - '9953:9944'
    extra_hosts:
    - "host.docker.internal:host-gateway"
    profiles:
    - astar
  
  validator6:
    image: 'analoglabs/timechain-node'
    command:
    - '--validator'
    - '--base-path=/data'
    - '--chain=dev'
    - '--rpc-cors=all'
    - '--unsafe-rpc-external'
    - '--rpc-methods=unsafe'
    - '--offchain-worker=Always'
    - '--connector-url=ws://ethereum:8545'
    - '--connector-blockchain=ethereum'
    - '--connector-network=dev'
    - '--network=ethereum'
    - '--keyfile=/etc/eth_keyfile4'
    - '--dave'
    - '--node-key=0000000000000000000000000000000000000000000000000000000000000004'
    - '--bootnodes=/dns4/bootnode/tcp/30333/p2p/12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp'
    environment:
      RUST_LOG: 'tesseract_tss=debug,time-worker=debug'
    depends_on:
    - bootnode
    - ethereum-connector
    volumes:
    - './dummy_wallets/eth_keyfile4:/etc/eth_keyfile4'
    - 'validator6-volume:/data'
    ports:
    - '9955:9944'
    extra_hosts:
    - "host.docker.internal:host-gateway"
    profiles:
    - ethereum

  validator7:
    image: 'analoglabs/timechain-node'
    command:
    - '--validator'
    - '--base-path=/data'
    - '--chain=dev'
    - '--rpc-cors=all'
    - '--unsafe-rpc-external'
    - '--rpc-methods=unsafe'
    - '--offchain-worker=Always'
    - '--connector-url=ws://ethereum:8545'
    - '--connector-blockchain=ethereum'
    - '--connector-network=dev'
    - '--network=ethereum'
    - '--keyfile=/etc/eth_keyfile5'
    - '--eve'
    - '--node-key=0000000000000000000000000000000000000000000000000000000000000005'
    - '--bootnodes=/dns4/bootnode/tcp/30333/p2p/12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp'
    environment:
      RUST_LOG: 'tesseract_tss=debug,time-worker=debug'
    depends_on:
    - bootnode
    - ethereum-connector
    volumes:
    - './dummy_wallets/eth_keyfile5:/etc/eth_keyfile5'
    - 'validator7-volume:/data'
    ports:
    - '9957:9944'
    extra_hosts:
    - "host.docker.internal:host-gateway"
    profiles:
    - ethereum

  validator8:
    image: 'analoglabs/timechain-node'
    command:
    - '--validator'
    - '--base-path=/data'
    - '--chain=dev'
    - '--rpc-cors=all'
    - '--unsafe-rpc-external'
    - '--rpc-methods=unsafe'
    - '--offchain-worker=Always'
    - '--connector-url=ws://ethereum:8545'
    - '--connector-blockchain=ethereum'
    - '--connector-network=dev'
    - '--network=ethereum'
    - '--keyfile=/etc/eth_keyfile6'
    - '--ferdie'
    - '--node-key=0000000000000000000000000000000000000000000000000000000000000006'
    - '--bootnodes=/dns4/bootnode/tcp/30333/p2p/12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp'
    environment:
      RUST_LOG: 'tesseract_tss=debug,time-worker=debug'
    depends_on:
    - bootnode
    - ethereum-connector
    volumes:
    - './dummy_wallets/eth_keyfile6:/etc/eth_keyfile6'
    - 'validator8-volume:/data'
    ports:
    - '9959:9944'
    extra_hosts:
    - "host.docker.internal:host-gateway"
    profiles:
    - ethereum

  ethereum:
    image: "ethereum/client-go:v1.12.2"
    command: "--dev --ipcdisable --dev.period 14 --http --http.addr 0.0.0.0 --http.vhosts * --http.api eth,debug,admin,txpool,web3"
    expose:
    - "8545"
    volumes:
    - "ethereum-volume:/root"
    profiles:
    - astar
    - ethereum

  astar:
    image: "staketechnologies/astar-collator:latest"
    platform: linux/amd64
    command: "astar-collator --chain dev --rpc-port 9944 --rpc-cors all --rpc-external --alice --enable-evm-rpc --base-path /astar"
    expose:
    - "9944"
    volumes:
    - "astar-volume:/astar"
    profiles:
    - astar

  pgsql:
    hostname: pgsql
    image: postgres:14-bullseye
    environment:
      - POSTGRES_DB=poc3
      - POSTGRES_USER=poc3
      - POSTGRES_PASSWORD=poc3
      - DB_PORT=5436
      - PGDATA=/var/lib/postgresql/data/pgdata
    command: -p 5436
    volumes:
      - pgsql-dbx-volume:/var/lib/postgresql/data
    ports:
      - "5436:5436"
