version: '3.9'
services:
  validator:
    image: 'analoglabs/timechain-node'
    command:
    - '--base-path=/data'
    - '--chain=dev'
    - '--rpc-cors=all'
    - '--unsafe-rpc-external'
    - '--rpc-methods=unsafe'
    - '--prometheus-external'
    - '--prometheus-port=9090'
    - '--alice'
    - '--validator'
    - '--node-key=0000000000000000000000000000000000000000000000000000000000000001'
    ports:
    - '9944:9944'
    labels:
      prometheus-scrape.enabled: 'true'

  ethereum:
    image: 'ethereum/client-go:v1.12.2'
    command:
    - '--dev'
    - '--ipcdisable'
    - '--dev.period=14'
    - '--ws'
    - '--ws.addr=0.0.0.0'
    - '--ws.port=8545'
    - '--ws.origins=*'
    - '--ws.api=eth,debug,admin,txpool,web3'
    expose:
    - '8545'
    ports:
    - '8545:8545'
    profiles:
    - ethereum

  astar:
    image: "staketechnologies/astar-collator:latest"
    command:
    - 'astar-collator'
    - '--base-path=/data'
    - '--chain=dev'
    - '--rpc-cors=all'
    - '--rpc-external'
    - '--alice'
    - '--enable-evm-rpc'
    - '--no-mdns'
    expose:
    - '9944'
    ports:
    - '9955:9944'
    profiles:
    - astar

  chronicle-eth1:
    image: 'analoglabs/timechain-node'
    command:
    - '--base-path=/data'
    - '--chain=dev'
    - '--rpc-cors=all'
    - '--unsafe-rpc-external'
    - '--rpc-methods=unsafe'
    - '--prometheus-external'
    - '--prometheus-port=9090'
    - '--bootnodes=/dns4/validator/tcp/30333/p2p/12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp'
    - '--url=ws://ethereum:8545'
    - '--blockchain=ethereum'
    - '--network=dev'
    - '--keyfile=/etc/keyfile'
    environment:
      RUST_LOG: 'chronicle=debug,tss=debug'
    depends_on:
    - validator
    - ethereum
    ports:
    - '9980:9944'
    volumes:
    - './config/wallets/eth_keyfile1:/etc/keyfile'
    labels:
      prometheus-scrape.enabled: 'true'
    profiles:
    - ethereum

  chronicle-eth2:
    image: 'analoglabs/timechain-node'
    command:
    - '--base-path=/data'
    - '--chain=dev'
    - '--rpc-cors=all'
    - '--unsafe-rpc-external'
    - '--rpc-methods=unsafe'
    - '--prometheus-external'
    - '--prometheus-port=9090'
    - '--bootnodes=/dns4/validator/tcp/30333/p2p/12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp'
    - '--url=ws://ethereum:8545'
    - '--blockchain=ethereum'
    - '--network=dev'
    - '--keyfile=/etc/keyfile'
    environment:
      RUST_LOG: 'chronicle=debug,tss=debug'
    depends_on:
    - validator
    - ethereum
    ports:
    - '9981:9944'
    volumes:
    - './config/wallets/eth_keyfile2:/etc/keyfile'
    labels:
      prometheus-scrape.enabled: 'true'
    profiles:
    - ethereum

  chronicle-eth3:
    image: 'analoglabs/timechain-node'
    command:
    - '--base-path=/data'
    - '--chain=dev'
    - '--rpc-cors=all'
    - '--unsafe-rpc-external'
    - '--rpc-methods=unsafe'
    - '--prometheus-external'
    - '--prometheus-port=9090'
    - '--bootnodes=/dns4/validator/tcp/30333/p2p/12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp'
    - '--url=ws://ethereum:8545'
    - '--blockchain=ethereum'
    - '--network=dev'
    - '--keyfile=/etc/keyfile'
    environment:
      RUST_LOG: 'chronicle=debug,tss=debug'
    depends_on:
    - validator
    - ethereum
    ports:
    - '9982:9944'
    volumes:
    - './config/wallets/eth_keyfile3:/etc/keyfile'
    labels:
      prometheus-scrape.enabled: 'true'
    profiles:
    - ethereum

  chronicle-astar1:
    image: 'analoglabs/timechain-node'
    command:
    - '--base-path=/data'
    - '--chain=dev'
    - '--rpc-cors=all'
    - '--unsafe-rpc-external'
    - '--rpc-methods=unsafe'
    - '--prometheus-external'
    - '--prometheus-port=9090'
    - '--bootnodes=/dns4/validator/tcp/30333/p2p/12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp'
    - '--url=ws://astar:9944'
    - '--blockchain=astar'
    - '--network=dev'
    - '--keyfile=/etc/keyfile'
    environment:
      RUST_LOG: 'chronicle=debug,tss=debug'
    depends_on:
    - validator
    - astar
    ports:
    - '9983:9944'
    volumes:
    - './config/wallets/astar_keyfile1:/etc/keyfile'
    labels:
      prometheus-scrape.enabled: 'true'
    profiles:
    - astar
  
  chronicle-astar2:
    image: 'analoglabs/timechain-node'
    command:
    - '--base-path=/data'
    - '--chain=dev'
    - '--rpc-cors=all'
    - '--unsafe-rpc-external'
    - '--rpc-methods=unsafe'
    - '--prometheus-external'
    - '--prometheus-port=9090'
    - '--bootnodes=/dns4/validator/tcp/30333/p2p/12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp'
    - '--url=ws://astar:9944'
    - '--blockchain=astar'
    - '--network=dev'
    - '--keyfile=/etc/keyfile'
    environment:
      RUST_LOG: 'chronicle=debug,tss=debug'
    depends_on:
    - validator
    - astar
    ports:
    - '9984:9944'
    volumes:
    - './config/wallets/astar_keyfile2:/etc/keyfile'
    labels:
      prometheus-scrape.enabled: 'true'
    profiles:
    - astar
  
  chronicle-astar3:
    image: 'analoglabs/timechain-node'
    command:
    - '--base-path=/data'
    - '--chain=dev'
    - '--rpc-cors=all'
    - '--unsafe-rpc-external'
    - '--rpc-methods=unsafe'
    - '--prometheus-external'
    - '--prometheus-port=9090'
    - '--bootnodes=/dns4/validator/tcp/30333/p2p/12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp'
    - '--url=ws://astar:9944'
    - '--blockchain=astar'
    - '--network=dev'
    - '--keyfile=/etc/keyfile'
    environment:
      RUST_LOG: 'chronicle=debug,tss=debug'
    depends_on:
    - validator
    - astar
    ports:
    - '9985:9944'
    volumes:
    - './config/wallets/astar_keyfile3:/etc/keyfile'
    labels:
      prometheus-scrape.enabled: 'true'
    profiles:
    - astar
