version: '3.9'
volumes:
  bootnode-volume:
  validator1-volume:
  validator2-volume:
  validator3-volume:
  validator4-volume:
  validator5-volume:
  ethereum-volume:
  ethereum-connector-volume:
  astar-volume:
  astar-connector-volume:
services:
  db:
    image: 'postgres'
    environment:
      POSTGRES_DB: timechain
      POSTGRES_PASSWORD: postgres
    ports:
    - '5432:5432'

  bootnode:
    image: 'analoglabs/timechain-node'
    command:
    - '--validator'
    - '--base-path=/data'
    - '--chain=local'
    - '--rpc-cors=all'
    - '--unsafe-rpc-external'
    - '--rpc-methods=unsafe'
    - '--offchain-worker=Always'
    - '--connector-url=http://ethereum-connector:8080'
    - '--connector-blockchain=ethereum'
    - '--connector-network=dev'
    - '--alice'
    - '--node-key=0000000000000000000000000000000000000000000000000000000000000001'
    environment:
      DATABASE_URL: 'postgresql://db/timechain?user=postgres&password=postgres'
    depends_on:
    - db
    - ethereum-connector
    volumes:
    - 'bootnode-volume:/data'
    ports:
    - '9943:9944'

  validator1:
    image: 'analoglabs/timechain-node'
    command:
    - '--validator'
    - '--base-path=/data'
    - '--chain=local'
    - '--rpc-cors=all'
    - '--unsafe-rpc-external'
    - '--rpc-methods=unsafe'
    - '--offchain-worker=Always'
    - '--connector-url=http://ethereum-connector:8080'
    - '--connector-blockchain=ethereum'
    - '--connector-network=dev'
    - '--bob'
    - '--bootnodes=/dns4/bootnode/tcp/30333/p2p/12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp'
    - '-ltime=trace'
    environment:
      DATABASE_URL: 'postgresql://db/timechain?user=postgres&password=postgres'
      RUST_LOG: 'tesseract_tss=debug,time-worker=debug,task-executor=debug'
    depends_on:
    - db
    - bootnode
    - ethereum-connector
    volumes:
    - 'validator1-volume:/data'
    ports:
    - '9945:9944'

  validator2:
    image: 'analoglabs/timechain-node'
    command:
    - '--validator'
    - '--base-path=/data'
    - '--chain=local'
    - '--rpc-cors=all'
    - '--unsafe-rpc-external'
    - '--rpc-methods=unsafe'
    - '--offchain-worker=Always'
    - '--connector-url=http://ethereum-connector:8080'
    - '--connector-blockchain=ethereum'
    - '--connector-network=dev'
    - '--charlie'
    - '--bootnodes=/dns4/bootnode/tcp/30333/p2p/12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp'
    - '-lthea=trace'
    environment:
      DATABASE_URL: 'postgresql://db/timechain?user=postgres&password=postgres'
    depends_on:
    - db
    - bootnode
    - ethereum-connector
    volumes:
    - 'validator2-volume:/data'
    ports:
    - '9947:9944'

  validator3:
    image: 'analoglabs/timechain-node'
    command:
    - '--validator'
    - '--base-path=/data'
    - '--chain=local'
    - '--rpc-cors=all'
    - '--unsafe-rpc-external'
    - '--rpc-methods=unsafe'
    - '--offchain-worker=Always'
    - '--connector-url=http://astar-connector:8081'
    - '--connector-blockchain=astar'
    - '--connector-network=dev'
    - '--dave'
    - '--bootnodes=/dns4/bootnode/tcp/30333/p2p/12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp'
    - '-lthea=trace'
    environment:
      DATABASE_URL: 'postgresql://db/timechain?user=postgres&password=postgres'
    depends_on:
    - db
    - bootnode
    - astar-connector
    volumes:
    - 'validator3-volume:/data'
    ports:
    - '9949:9944'

  validator4:
    image: 'analoglabs/timechain-node'
    command:
    - '--validator'
    - '--base-path=/data'
    - '--chain=local'
    - '--rpc-cors=all'
    - '--unsafe-rpc-external'
    - '--rpc-methods=unsafe'
    - '--offchain-worker=Always'
    - '--connector-url=http://astar-connector:8081'
    - '--connector-blockchain=astar'
    - '--connector-network=dev'
    - '--eve'
    - '--bootnodes=/dns4/bootnode/tcp/30333/p2p/12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp'
    - '-lthea=trace'
    environment:
      DATABASE_URL: 'postgresql://db/timechain?user=postgres&password=postgres'
    depends_on:
    - db
    - bootnode
    - astar-connector
    volumes:
    - 'validator4-volume:/data'
    ports:
    - '9951:9944'

  validator5:
    image: 'analoglabs/timechain-node'
    command:
    - '--validator'
    - '--base-path=/data'
    - '--chain=local'
    - '--rpc-cors=all'
    - '--unsafe-rpc-external'
    - '--rpc-methods=unsafe'
    - '--offchain-worker=Always'
    - '--connector-url=http://astar-connector:8081'
    - '--connector-blockchain=astar'
    - '--connector-network=dev'
    - '--ferdie'
    - '--bootnodes=/dns4/bootnode/tcp/30333/p2p/12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp'
    - '-lthea=trace'
    environment:
      DATABASE_URL: 'postgresql://db/timechain?user=postgres&password=postgres'
    depends_on:
    - db
    - bootnode
    - astar-connector
    volumes:
    - 'validator5-volume:/data'
    ports:
    - '9953:9944'

  ethereum:
    image: "ethereum/client-go:v1.10.26"
    command: "--dev --ipcdisable --dev.period 14 --http --http.addr 0.0.0.0 --http.vhosts * --http.api eth,debug,admin,txpool,web3"
    expose:
    - "8545"
    volumes:
    - "ethereum-volume:/root"

  ethereum-connector:
    image: "analoglabs/connector-ethereum"
    platform: linux/x86_64
    command: "--network dev --addr 0.0.0.0:8080 --node-addr ethereum:8545 --path /data"
    expose:
    - "8080"
    ports:
    - "8080:8080"
    depends_on:
    - ethereum
    volumes:
    - "ethereum-connector-volume:/data"
    restart: always

  astar:
    image: "staketechnologies/astar-collator:latest"
    platform: linux/x86_64
    command: "astar-collator --chain dev --ws-port 9944 --rpc-port 9955 --rpc-cors all --ws-external --alice --blocks-pruning archive --state-pruning archive --base-path /astar"
    expose:
    - "9944"
    - "9955"
    volumes:
    - "astar-volume:/astar"

  astar-connector:
    image: "analoglabs/connector-astar"
    platform: linux/x86_64
    command: "--network dev --addr 0.0.0.0:8081 --node-addr astar:9944 --path /data"
    expose:
    - "8081"
    ports:
    - "8081:8081"
    depends_on:
    - astar
    volumes:
    - "astar-connector-volume:/data"
    restart: always
