version: '3.9'
volumes:
  bootnode-volume:
  validator1-volume:
  validator2-volume:
services:
  db:
    image: 'postgres'
    environment:
      POSTGRES_DB: timechain
      POSTGRES_PASSWORD: postgres
    ports:
    - '5432:5432'

  bootnode:
    image: 'analoglabs/timechain-node'
    command:
    - '--validator'
    - '--base-path=/data'
    - '--chain=local'
    - '--rpc-cors=all'
    - '--unsafe-rpc-external'
    - '--unsafe-ws-external'
    - '--rpc-methods=unsafe'
    - '--connector-url=http://rosetta.analog.one:8081'
    - '--connector-blockchain=ethereum'
    - '--connector-network=dev'
    - '--alice'
    - '--node-key=0000000000000000000000000000000000000000000000000000000000000001'
    environment:
      DATABASE_URL: 'postgresql://db/timechain?user=postgres&password=postgres'
    depends_on:
    - db
    volumes:
    - 'bootnode-volume:/data'
    ports:
    - '9943:9944'
    - '9944:9933'

  validator1:
    image: 'analoglabs/timechain-node'
    command:
    - '--validator'
    - '--base-path=/data'
    - '--chain=local'
    - '--rpc-cors=all'
    - '--unsafe-rpc-external'
    - '--unsafe-ws-external'
    - '--rpc-methods=unsafe'
    - '--connector-url=http://rosetta.analog.one:8081'
    - '--connector-blockchain=ethereum'
    - '--connector-network=dev'
    - '--bob'
    - '--bootnodes=/dns4/bootnode/tcp/30333/p2p/12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp'
    - '-ltime=trace'
    environment:
      DATABASE_URL: 'postgresql://db/timechain?user=postgres&password=postgres'
    depends_on:
    - db
    - bootnode
    volumes:
    - 'validator1-volume:/data'
    ports:
    - '9945:9944'
    - '9946:9933'

  validator2:
    image: 'analoglabs/timechain-node'
    command:
    - '--validator'
    - '--base-path=/data'
    - '--chain=local'
    - '--rpc-cors=all'
    - '--unsafe-rpc-external'
    - '--unsafe-ws-external'
    - '--rpc-methods=unsafe'
    - '--connector-url=http://rosetta.analog.one:8081'
    - '--connector-blockchain=ethereum'
    - '--connector-network=dev'
    - '--charlie'
    - '--bootnodes=/dns4/bootnode/tcp/30333/p2p/12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp'
    - '-lthea=trace'
    environment:
      DATABASE_URL: 'postgresql://db/timechain?user=postgres&password=postgres'
    depends_on:
    - db
    - bootnode
    volumes:
    - 'validator2-volume:/data'
    ports:
    - '9947:9944'
    - '9948:9933'
