version: "3.2"

services:
  dev2:
    container_name: node-template2
    image: paritytech/ci-linux:production
    volumes:
      - type: bind
        source: /home/ubuntu/actions-runner/_work/testnet/testnet
        target: /builds
    command: bash -c "./target/release/node-template --dev --ws-external"
    
    networks:
      - nodenetwork
