version: "3.2"

services:
  dev:
    container_name: node-template
    image: paritytech/ci-linux:production
    ports:
      - "9944:9944"
      - "9933:9933"
    volumes:
      - type: bind
        source: /home/ubuntu/actions-runner/_work/testnet/testnet
        target: /builds
    command: bash -c "cargo build --release && ./target/release/node-template --dev --ws-external"
