version: '3.9'
volumes:
  bootnode-volume:
  validator1-volume:
  validator2-volume:
  validator3-volume:
  validator4-volume:
  validator5-volume:
  ethereum-volume:
  ethereum-connector-volume:
  astar-volume:
  astar-connector-volume:
  pgsql-dbx-volume:
services:
  bootnode:
    image: 'analoglabs/timechain-node'
    command:
    - '--validator'
    - '--base-path=/data'
    - '--chain=dev'
    - '--rpc-cors=all'
    - '--unsafe-rpc-external'
    - '--rpc-methods=unsafe'
    - '--offchain-worker=Always'
    - '--connector-url=http://ethereum-connector:8080'
    - '--connector-blockchain=ethereum'
    - '--connector-network=dev'
    - '--alice'
    - '--node-key=0000000000000000000000000000000000000000000000000000000000000001'
    environment:
      TIMEGRAPH_GRAPHQL_URL: ${TIMEGRAPH_GRAPHQL_URL}
      SSK: ${SSK}
    depends_on:
    - ethereum-connector
    - timegraph
    volumes:
    - 'bootnode-volume:/data'
    ports:
    - '9943:9944'
    extra_hosts:
    - "host.docker.internal:host-gateway"

  validator1:
    image: 'analoglabs/timechain-node'
    command:
    - '--validator'
    - '--base-path=/data'
    - '--chain=dev'
    - '--rpc-cors=all'
    - '--unsafe-rpc-external'
    - '--rpc-methods=unsafe'
    - '--offchain-worker=Always'
    - '--connector-url=http://ethereum-connector:8080'
    - '--connector-blockchain=ethereum'
    - '--connector-network=dev'
    - '--bob'
    - '--node-key=0000000000000000000000000000000000000000000000000000000000000002'
    - '--bootnodes=/dns4/bootnode/tcp/30333/p2p/12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp'
    environment:
      TIMEGRAPH_GRAPHQL_URL: ${TIMEGRAPH_GRAPHQL_URL}
      SSK: ${SSK}
      RUST_LOG: 'tesseract_tss=debug,time-worker=debug,task-executor=debug'
    depends_on:
    - bootnode
    - ethereum-connector
    - timegraph
    volumes:
    - 'validator1-volume:/data'
    ports:
    - '9945:9944'
    extra_hosts:
    - "host.docker.internal:host-gateway"

  validator2:
    image: 'analoglabs/timechain-node'
    command:
    - '--validator'
    - '--base-path=/data'
    - '--chain=dev'
    - '--rpc-cors=all'
    - '--unsafe-rpc-external'
    - '--rpc-methods=unsafe'
    - '--offchain-worker=Always'
    - '--connector-url=http://ethereum-connector:8080'
    - '--connector-blockchain=ethereum'
    - '--connector-network=dev'
    - '--charlie'
    - '--node-key=0000000000000000000000000000000000000000000000000000000000000003'
    - '--bootnodes=/dns4/bootnode/tcp/30333/p2p/12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp'
    environment:
      TIMEGRAPH_GRAPHQL_URL: ${TIMEGRAPH_GRAPHQL_URL}
      SSK: ${SSK}
      RUST_LOG: 'tesseract_tss=debug,time-worker=debug'
    depends_on:
    - bootnode
    - ethereum-connector
    - timegraph
    volumes:
    - 'validator2-volume:/data'
    ports:
    - '9947:9944'
    extra_hosts:
    - "host.docker.internal:host-gateway"

  validator3:
    image: 'analoglabs/timechain-node'
    command:
    - '--validator'
    - '--base-path=/data'
    - '--chain=dev'
    - '--rpc-cors=all'
    - '--unsafe-rpc-external'
    - '--rpc-methods=unsafe'
    - '--offchain-worker=Always'
    - '--connector-url=http://astar-connector:8081'
    - '--connector-blockchain=astar'
    - '--connector-network=dev'
    - '--dave'
    - '--node-key=0000000000000000000000000000000000000000000000000000000000000004'
    - '--bootnodes=/dns4/bootnode/tcp/30333/p2p/12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp'
    environment:
      TIMEGRAPH_GRAPHQL_URL: ${TIMEGRAPH_GRAPHQL_URL}
      SSK: ${SSK}
      RUST_LOG: 'tesseract_tss=debug,time-worker=debug'
    depends_on:
    - bootnode
    - astar-connector
    - timegraph
    volumes:
    - 'validator3-volume:/data'
    ports:
    - '9949:9944'
    extra_hosts:
    - "host.docker.internal:host-gateway"

  validator4:
    image: 'analoglabs/timechain-node'
    command:
    - '--validator'
    - '--base-path=/data'
    - '--chain=dev'
    - '--rpc-cors=all'
    - '--unsafe-rpc-external'
    - '--rpc-methods=unsafe'
    - '--offchain-worker=Always'
    - '--connector-url=http://astar-connector:8081'
    - '--connector-blockchain=astar'
    - '--connector-network=dev'
    - '--eve'
    - '--node-key=0000000000000000000000000000000000000000000000000000000000000005'
    - '--bootnodes=/dns4/bootnode/tcp/30333/p2p/12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp'
    environment:
      TIMEGRAPH_GRAPHQL_URL: ${TIMEGRAPH_GRAPHQL_URL}
      SSK: ${SSK}
      RUST_LOG: 'tesseract_tss=debug,time-worker=debug'
    depends_on:
    - bootnode
    - astar-connector
    - timegraph
    volumes:
    - 'validator4-volume:/data'
    ports:
    - '9951:9944'
    extra_hosts:
    - "host.docker.internal:host-gateway"

  validator5:
    image: 'analoglabs/timechain-node'
    command:
    - '--validator'
    - '--base-path=/data'
    - '--chain=dev'
    - '--rpc-cors=all'
    - '--unsafe-rpc-external'
    - '--rpc-methods=unsafe'
    - '--offchain-worker=Always'
    - '--connector-url=http://astar-connector:8081'
    - '--connector-blockchain=astar'
    - '--connector-network=dev'
    - '--ferdie'
    - '--node-key=0000000000000000000000000000000000000000000000000000000000000006'
    - '--bootnodes=/dns4/bootnode/tcp/30333/p2p/12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp'
    environment:
      TIMEGRAPH_GRAPHQL_URL: ${TIMEGRAPH_GRAPHQL_URL}
      SSK: ${SSK}
      RUST_LOG: 'tesseract_tss=debug,time-worker=debug'
    depends_on:
    - bootnode
    - astar-connector
    - timegraph
    volumes:
    - 'validator5-volume:/data'
    ports:
    - '9953:9944'
    extra_hosts:
    - "host.docker.internal:host-gateway"

  ethereum:
    image: "ethereum/client-go:v1.10.26"
    command: "--dev --ipcdisable --dev.period 14 --http --http.addr 0.0.0.0 --http.vhosts * --http.api eth,debug,admin,txpool,web3"
    expose:
    - "8545"
    volumes:
    - "ethereum-volume:/root"

  ethereum-connector:
    image: "analoglabs/connector-ethereum"
    platform: linux/amd64
    command: "--network dev --addr 0.0.0.0:8080 --node-addr http://ethereum:8545"
    expose:
    - "8080"
    ports:
    - "8080:8080"
    depends_on:
    - ethereum
    volumes:
    - "ethereum-connector-volume:/data"
    restart: always

  astar:
    image: "staketechnologies/astar-collator:latest"
    platform: linux/amd64
    command: "astar-collator --chain dev --rpc-port 9944 --rpc-cors all --rpc-external --alice --enable-evm-rpc --base-path /astar"
    expose:
    - "9944"
    volumes:
    - "astar-volume:/astar"

  astar-connector:
    image: "analoglabs/connector-astar"
    platform: linux/amd64
    command: "--network dev --addr 0.0.0.0:8081 --node-addr ws://astar:9944"
    expose:
    - "8081"
    ports:
    - "8081:8081"
    depends_on:
    - astar
    volumes:
    - "astar-connector-volume:/data"
    restart: always

  pgsql:
    hostname: pgsql
    image: postgres:14-bullseye
    environment:
      - POSTGRES_DB=poc3
      - POSTGRES_USER=poc3
      - POSTGRES_PASSWORD=poc3
      - DB_PORT=5436
      - PGDATA=/var/lib/postgresql/data/pgdata
    command: -p 5436
    volumes:
      - pgsql-dbx-volume:/var/lib/postgresql/data
    ports:
      - "5436:5436"

  timegraph:
    build: ./docker/timegraph
    hostname: timegraph
    environment:
      - GENESIS=yes
      - ANALOG_DB_URL=postgres://poc3:poc3@pgsql:5436/poc3
      - WAIT_HOSTS=pgsql:5436
      - RUST_LOG=debug
    command: serve --at 0.0.0.0:8008 --rpc ws://bootnode:9944 -k developer
    ports:
      - "8008:8008"
    depends_on:
      - pgsql

  timegraph-sync:
    build: ./docker/timegraph
    hostname: timegraph-sync
    environment:
      - WAIT_HOSTS=pgsql:5436,bootnode:9944
      - ANALOG_DB_URL=postgres://poc3:poc3@pgsql:5436/poc3
      - RUST_LOG=debug
    command: sync --rpc ws://bootnode:9944 --interval 3 --signer 22tya3QVJBCxPAskCqfKLxH8cg1qRrtzLpxFakH6T7WBQmdpQErBEcaihetUNenpc6qiAvkMBb9TQ5ii1ycFDddz
    depends_on:
      - bootnode
      - pgsql
