version: "3.2"

services:
  dev:
    container_name: node-template
    image: paritytech/ci-linux:production
    ports:
      - "9900:9933"
      - "9944:9944"
    volumes:
      - type: bind
        source: /home/ubuntu/actions-runner/_work/testnet/testnet
        target: /builds
    command: bash -c "./target/release/node-template --dev --ws-external"
    networks:
      - nodenetwork

    container_name: node-template1
    image: paritytech/ci-linux:production
    volumes:
      - type: bind
        source: /home/ubuntu/actions-runner/_work/testnet/testnet
        target: /builds
    command: bash -c "./target/release/node-template --dev --ws-external"
    networks:
      - nodenetwork

    container_name: node-template2
    image: paritytech/ci-linux:production
    volumes:
      - type: bind
        source: /home/ubuntu/actions-runner/_work/testnet/testnet
        target: /builds
    command: bash -c "./target/release/node-template --dev --ws-external"
    networks:
      - nodenetwork  
       
networks:
  nodenetwork:
