[package]
name = "analog-vesting"
authors = [ "Analog Devs <https://github.com/analog-labs>" ]
description = "A pallet for vesting."
edition = "2021"
homepage = "https://analog.one"
license = "Unlicense"
publish = false
repository = "https://github.com/Analog-Labs/testnet"
version = "4.0.0-dev"
[dependencies]
codec = { package = "parity-scale-codec", version = "3.6.3", default-features = false, features = [ "max-encoded-len" ] }
scale-info = { version = "2.9.0", default-features = false, features = [ "derive" ] }
serde = { version = "1.0", optional = true }

frame-support = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v1.0.0", version = "4.0.0-dev", default-features = false }
frame-system = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v1.0.0", version = "4.0.0-dev", default-features = false }
sp-io = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0", default-features = false }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0", default-features = false }
sp-std = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0", default-features = false }

[dev-dependencies]
pallet-balances = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0" }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0" }

[features]
default = [ "std" ]
std = [
	"codec/std",
	"frame-support/std",
	"frame-system/std",
	"scale-info/std",
	"serde",
	"sp-io/std",
	"sp-runtime/std",
	"sp-std/std",
]
runtime-benchmarks = [
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
]
try-runtime = [
	"frame-support/try-runtime",
	"frame-system/try-runtime",
]
