[dependencies]
codec = { default-features = false, features = [ "max-encoded-len" ], package = "parity-scale-codec", version = "3.6.3" }
scale-info = { default-features = false, features = [ "derive" ], version = "2.9.0" }
serde = { optional = true, version = "1.0" }

frame-support = { branch = "polkadot-v1.0.0", default-features = false, git = "https://github.com/paritytech/substrate.git", version = "4.0.0-dev" }
frame-system = { branch = "polkadot-v1.0.0", default-features = false, git = "https://github.com/paritytech/substrate.git", version = "4.0.0-dev" }
sp-io = { branch = "polkadot-v1.0.0", default-features = false, git = "https://github.com/paritytech/substrate" }
sp-runtime = { branch = "polkadot-v1.0.0", default-features = false, git = "https://github.com/paritytech/substrate" }
sp-std = { branch = "polkadot-v1.0.0", default-features = false, git = "https://github.com/paritytech/substrate" }

[dev-dependencies]
pallet-balances = { branch = "polkadot-v1.0.0", git = "https://github.com/paritytech/substrate" }
sp-core = { branch = "polkadot-v1.0.0", git = "https://github.com/paritytech/substrate" }

[features]
default = [ "std" ]
runtime-benchmarks = [
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
]
std = [
	"serde",
	"codec/std",
	"frame-support/std",
	"frame-system/std",
	"scale-info/std",
	"sp-io/std",
	"sp-runtime/std",
	"sp-std/std",
]
try-runtime = [
	"frame-support/try-runtime",
	"frame-system/try-runtime",
]
[package]
authors = [ "Analog Devs <https://github.com/analog-labs>" ]
description = "A pallet for vesting."
edition = "2021"
homepage = "https://analog.one"
license = "Unlicense"
name = "analog-vesting"
publish = false
repository = "https://github.com/Analog-Labs/testnet"
version = "4.0.0-dev"
