[package]
name = "chronicle"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy-primitives = { version = "0.6.4" }
alloy-sol-types = { version = "0.6.4" }
anyhow = "1.0.75"
async-trait = "0.1.73"
clap = { version = "4.4.18", features = ["derive"] }
futures = "0.3.28"
hex = "0.4"
peernet = "0.1.2"
rosetta-client.workspace = true
rosetta-core.workspace = true
rosetta-config-ethereum.workspace = true
schnorr-evm = { version = "0.1.0" }
serde = "1.0.188"
serde_json = "1.0.105"
sha3 = { version = "0.10" }
tc-subxt = { path = "../tc-subxt" }
time-primitives = { path = "../primitives" }
tokio = "1.32.0"
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
tss = { path = "../tss" }
prometheus_exporter = { version = "0.8.5", default-features = false, features = ["logging"] }

[dev-dependencies]
env_logger = "0.10.0"
log-panics = "2.1.0"
lazy_static = "1.4.0"
surf = { version = "2.3.2", default-features = false, features = [ "h1-client-rustls" ] }
