[package]
name = "chronicle"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy-primitives = { version = "0.5" }
alloy-sol-types = { version = "0.5" }
anyhow = "1.0.75"
async-channel = "1.9.0"
bincode = "1.3.3"
dirs = "5.0.1"
futures = "0.3.28"
hex = "0.4"
peernet = "0.1.1"
rosetta-client = { git = "https://github.com/analog-labs/chain-connectors", branch = "master" }
rosetta-core = { git = "https://github.com/analog-labs/chain-connectors", branch = "master" }
rosetta-config-ethereum = { git = "https://github.com/analog-labs/chain-connectors", branch = "master" }
sc-client-api = { git = "https://github.com/Analog-Labs/polkadot-sdk.git", branch = "timechain/full-tracing" }
sc-network = { git = "https://github.com/Analog-Labs/polkadot-sdk.git", branch = "timechain/full-tracing" }
sc-transaction-pool-api = { git = "https://github.com/Analog-Labs/polkadot-sdk.git", branch = "timechain/full-tracing" }
schnorr-evm = { git = "https://github.com/Analog-labs/frost-evm.git", version = "0.1.0" }
serde = "1.0.188"
serde_json = "1.0.105"
sha3 = { version = "0.10" }
sp-api = { git = "https://github.com/Analog-Labs/polkadot-sdk.git", branch = "timechain/full-tracing" }
sp-keystore = { git = "https://github.com/Analog-Labs/polkadot-sdk.git", branch = "timechain/full-tracing" }
sp-runtime = { git = "https://github.com/Analog-Labs/polkadot-sdk.git", branch = "timechain/full-tracing" }
tc-subxt = { path = "../tc-subxt" }
time-primitives = { path = "../primitives" }
timegraph-client = "0.1.10"
tokio = "1.32.0"
tracing = "0.1.37"
tss = { path = "../tss" }
clap = { version = "4.4.18", features = ["derive"] }

[dev-dependencies]
env_logger = "0.10.0"
sc-consensus = { git = "https://github.com/Analog-Labs/polkadot-sdk.git", branch = "timechain/full-tracing" }
sc-network-test = { git = "https://github.com/Analog-Labs/polkadot-sdk.git", branch = "timechain/full-tracing" }
sp-core = { git = "https://github.com/Analog-Labs/polkadot-sdk.git", branch = "timechain/full-tracing", default-features = false}
surf = { version = "2.3.2", default-features = false, features = [ "h1-client-rustls" ] }
sc-block-builder = { git = "https://github.com/Analog-Labs/polkadot-sdk.git", branch = "timechain/full-tracing" }
sp-consensus = { git = "https://github.com/Analog-Labs/polkadot-sdk.git", branch = "timechain/full-tracing" }
substrate-test-runtime-client = {  git = "https://github.com/Analog-Labs/polkadot-sdk.git", branch = "timechain/full-tracing" }
log-panics = "2.1.0"
lazy_static = "1.4.0"
