[package]
name = "chronicle"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
async-channel = "1.9.0"
async-trait = "0.1.73"
bincode = "1.3.3"
futures = "0.3.28"
hex = "0.4"
rosetta-client = { git = "https://github.com/analog-labs/chain-connectors", branch = "master" }
rosetta-core = { git = "https://github.com/analog-labs/chain-connectors", branch = "master" }
sc-client-api = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "master" }
sc-network = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "master" }
sc-transaction-pool-api = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "master" }
serde = "1.0.188"
serde_json = "1.0.105"
sp-api = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "master" }
sp-keystore = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "master" }
sp-runtime = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "master" }
time-primitives = { path = "../primitives" }
timegraph-client = "0.1.9"
tokio = "1.32.0"
tracing = "0.1.37"
tss = { path = "../tss" }

[dev-dependencies]
env_logger = "0.10.0"
sc-consensus = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "master" }
sc-network-test = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "master" }
schnorr-evm = { git = "https://github.com/Analog-labs/frost-evm.git", version = "0.1.0" }
surf = { version = "2.3.2", default-features = false, features = [ "h1-client-rustls" ] }
sp-consensus = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "master" }
sp-core = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "master", default-features = false}
sc-block-builder = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "master" }
substrate-test-runtime-client = {  git = "https://github.com/paritytech/polkadot-sdk.git", branch = "master" }
lazy_static = "1.4.0"
log-panics = "2.1.0"
