[package]
name = "chronicle"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy-primitives = { version = "0.5" }
alloy-sol-types = { version = "0.5" }
anyhow = "1.0.75"
async-trait = "0.1.73"
clap = { version = "4.4.18", features = ["derive"] }
futures = "0.3.28"
hex = "0.4"
peernet = "0.1.2"
rosetta-client = { git = "https://github.com/analog-labs/chain-connectors", rev = "f75bd6a0a56633e74945fa12e1d1830a63f70507" }
rosetta-core = { git = "https://github.com/analog-labs/chain-connectors", rev = "f75bd6a0a56633e74945fa12e1d1830a63f70507" }
rosetta-config-ethereum = { git = "https://github.com/analog-labs/chain-connectors", rev = "f75bd6a0a56633e74945fa12e1d1830a63f70507" }
schnorr-evm = { version = "0.1.0" }
serde = "1.0.188"
serde_json = "1.0.105"
sha3 = { version = "0.10" }
tc-subxt = { path = "../tc-subxt" }
time-primitives = { path = "../primitives" }
timegraph-client = "0.1.10"
tokio = "1.32.0"
tracing = "0.1.37"
tracing-subscriber = "0.3.18"
tss = { path = "../tss" }

[dev-dependencies]
env_logger = "0.10.0"
log-panics = "2.1.0"
lazy_static = "1.4.0"
surf = { version = "2.3.2", default-features = false, features = [ "h1-client-rustls" ] }
