[build-dependencies]
substrate-wasm-builder = { branch = "polkadot-v1.0.0", git = "https://github.com/paritytech/substrate.git" }

[dependencies]
codec = { default-features = false, features = [ "derive" ], package = "parity-scale-codec", version = "3.6.3" }
log = { default-features = false, version = "0.4.19" }
scale-info = { default-features = false, features = [ "derive" ], version = "2.9.0" }
static_assertions = "1.1.0"

frame-election-provider-support = { branch = "polkadot-v1.0.0", default-features = false, git = "https://github.com/paritytech/substrate.git" }
pallet-babe = { branch = "polkadot-v1.0.0", default-features = false, git = "https://github.com/paritytech/substrate.git" }
pallet-bags-list = { branch = "polkadot-v1.0.0", default-features = false, git = "https://github.com/paritytech/substrate.git" }
pallet-balances = { branch = "polkadot-v1.0.0", default-features = false, git = "https://github.com/paritytech/substrate.git" }
pallet-collective  = { branch = "polkadot-v1.0.0", default-features = false, git = "https://github.com/paritytech/substrate.git" }
pallet-im-online = { branch = "polkadot-v1.0.0", default-features = false, git = "https://github.com/paritytech/substrate.git" }
pallet-offences = { branch = "polkadot-v1.0.0", default-features = false, git = "https://github.com/paritytech/substrate.git" }
pallet-session = { branch = "polkadot-v1.0.0", default-features = false, features = [ "historical" ], git = "https://github.com/paritytech/substrate.git" }
pallet-staking = { branch = "polkadot-v1.0.0", default-features = false, git = "https://github.com/paritytech/substrate.git" }
pallet-staking-reward-curve = { branch = "polkadot-v1.0.0", git = "https://github.com/paritytech/substrate.git" }

pallet-authorship = { branch = "polkadot-v1.0.0", default-features = false, git = "https://github.com/paritytech/substrate.git" }
pallet-election-provider-multi-phase = { branch = "polkadot-v1.0.0", default-features = false, git = "https://github.com/paritytech/substrate.git" }

sp-io = { branch = "polkadot-v1.0.0", default-features = false, git = "https://github.com/paritytech/substrate.git" }

frame-executive = { branch = "polkadot-v1.0.0", default-features = false, git = "https://github.com/paritytech/substrate.git" }
frame-support = { branch = "polkadot-v1.0.0", default-features = false, git = "https://github.com/paritytech/substrate.git" }
frame-system = { branch = "polkadot-v1.0.0", default-features = false, git = "https://github.com/paritytech/substrate.git" }
frame-try-runtime = { branch = "polkadot-v1.0.0", default-features = false, git = "https://github.com/paritytech/substrate.git", optional = true }
pallet-grandpa = { branch = "polkadot-v1.0.0", default-features = false, git = "https://github.com/paritytech/substrate.git" }
pallet-sudo = { branch = "polkadot-v1.0.0", default-features = false, git = "https://github.com/paritytech/substrate.git" }
pallet-timestamp = { branch = "polkadot-v1.0.0", default-features = false, git = "https://github.com/paritytech/substrate.git" }
pallet-transaction-payment = { branch = "polkadot-v1.0.0", default-features = false, git = "https://github.com/paritytech/substrate.git" }
pallet-utility = { branch = "polkadot-v1.0.0", default-features = false, git = "https://github.com/paritytech/substrate.git" }
sp-api = { branch = "polkadot-v1.0.0", default-features = false, git = "https://github.com/paritytech/substrate.git" }
sp-block-builder = { branch = "polkadot-v1.0.0", default-features = false, git = "https://github.com/paritytech/substrate.git" }
sp-consensus-babe = { branch = "polkadot-v1.0.0", default-features = false, git = "https://github.com/paritytech/substrate.git" }

sp-core = { branch = "polkadot-v1.0.0", default-features = false, git = "https://github.com/paritytech/substrate.git" }
sp-inherents = { branch = "polkadot-v1.0.0", default-features = false, git = "https://github.com/paritytech/substrate.git" }
sp-offchain = { branch = "polkadot-v1.0.0", default-features = false, git = "https://github.com/paritytech/substrate.git" }
sp-runtime = { branch = "polkadot-v1.0.0", default-features = false, git = "https://github.com/paritytech/substrate.git" }
sp-session = { branch = "polkadot-v1.0.0", default-features = false, git = "https://github.com/paritytech/substrate.git" }
sp-std = { branch = "polkadot-v1.0.0", default-features = false, git = "https://github.com/paritytech/substrate.git" }
sp-transaction-pool = { branch = "polkadot-v1.0.0", default-features = false, git = "https://github.com/paritytech/substrate.git" }
sp-version = { branch = "polkadot-v1.0.0", default-features = false, git = "https://github.com/paritytech/substrate.git" }

sp-npos-elections = { branch = "polkadot-v1.0.0", default-features = false, git = "https://github.com/paritytech/substrate.git" }
sp-staking = { branch = "polkadot-v1.0.0", default-features = false, git = "https://github.com/paritytech/substrate.git" }

sp-arithmetic = { branch = "polkadot-v1.0.0", default-features = false, git = "https://github.com/paritytech/substrate.git" }


# Used for the node template's RPCs
frame-system-rpc-runtime-api = { branch = "polkadot-v1.0.0", default-features = false, git = "https://github.com/paritytech/substrate.git" }
pallet-transaction-payment-rpc-runtime-api = { branch = "polkadot-v1.0.0", default-features = false, git = "https://github.com/paritytech/substrate.git" }

# Used for runtime benchmarking
frame-benchmarking = { branch = "polkadot-v1.0.0", default-features = false, git = "https://github.com/paritytech/substrate.git", optional = true }
frame-system-benchmarking = { branch = "polkadot-v1.0.0", default-features = false, git = "https://github.com/paritytech/substrate.git", optional = true }

# Local Dependencies
analog-vesting = { default-features = false, path = "../pallets/vesting", version = "4.0.0-dev" }
pallet-ocw = { default-features = false, path = "../pallets/ocw", version = "4.0.0-dev" }
pallet-shards = { default-features = false, path = "../pallets/shards", version = "4.0.0-dev" }
pallet-tasks = { default-features = false, path = "../pallets/tasks", version = "0.0.1" }
pallet-treasury = { branch = "polkadot-v1.0.0", default-features = false, git = "https://github.com/paritytech/substrate.git" }
runtime-common = { default-features = false, path = "./common" }
time-primitives = { default-features = false, path = "../primitives" }

[dev-dependencies]
separator = "0.4.1"

[features]
default = [ "std" ]
runtime-benchmarks = [
	"frame-benchmarking/runtime-benchmarks",
	"frame-support/runtime-benchmarks",
	"frame-system-benchmarking/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"pallet-balances/runtime-benchmarks",
	"pallet-grandpa/runtime-benchmarks",
	"pallet-im-online/runtime-benchmarks",
	"pallet-shards/runtime-benchmarks",
	"pallet-timestamp/runtime-benchmarks",
	"analog-vesting/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"pallet-treasury/runtime-benchmarks",
	"pallet-tasks/runtime-benchmarks",
	"pallet-collective/runtime-benchmarks",
]
std = [
	"frame-try-runtime?/std",
	"frame-system-benchmarking?/std",
	"frame-benchmarking?/std",
	"codec/std",
	"scale-info/std",
	"frame-executive/std",
	"frame-support/std",
	"frame-system-rpc-runtime-api/std",
	"frame-system/std",
	"frame-try-runtime/std",
	"frame-election-provider-support/std",
	"pallet-authorship/std",
	"pallet-babe/std",
	"pallet-bags-list/std",
	"pallet-balances/std",
	"pallet-im-online/std",
	"pallet-offences/std",
	"pallet-session/std",
	"pallet-grandpa/std",
	"pallet-election-provider-multi-phase/std",
	"pallet-sudo/std",
	"pallet-staking/std",
	"pallet-collective/std",
	"analog-vesting/std",
	"pallet-utility/std",
	"pallet-shards/std",
	"pallet-timestamp/std",
	"pallet-transaction-payment-rpc-runtime-api/std",
	"pallet-transaction-payment/std",
	"pallet-treasury/std",
	"sp-api/std",
	"sp-arithmetic/std",
	"sp-block-builder/std",
	"sp-consensus-babe/std",
	"sp-core/std",
	"sp-inherents/std",
	"sp-offchain/std",
	"sp-runtime/std",
	"sp-session/std",
	"sp-npos-elections/std",
	"sp-staking/std",
	"sp-std/std",
	"sp-transaction-pool/std",
	"sp-version/std",
	"time-primitives/std",
	"pallet-tasks/std",
]
try-runtime = [
	"frame-try-runtime",
	"frame-executive/try-runtime",
	"frame-system/try-runtime",
	"frame-support/try-runtime",
	"pallet-babe/try-runtime",
	"pallet-balances/try-runtime",
	"pallet-grandpa/try-runtime",
	"pallet-im-online/try-runtime",
	"pallet-sudo/try-runtime",
	"pallet-shards/try-runtime",
	"pallet-timestamp/try-runtime",
	"pallet-transaction-payment/try-runtime",
	"analog-vesting/try-runtime",
	"pallet-treasury/try-runtime",
	"pallet-authorship/try-runtime",
	"pallet-tasks/try-runtime",
]
[package]
authors = [ "Analog Devs <https://github.com/Analog-Labs>" ]
description = "A blockchain using the proof of time consensus protocol"
edition = "2021"
homepage = "https://analog.one/"
name = "timechain-runtime"
repository = "https://github.com/Analog-Labs/testnet/"
version = "0.0.1"

[package.metadata.docs.rs]
targets = [ "x86_64-unknown-linux-gnu" ]
