config:
  chronicle_funds: 10.
  timechain_url: 'ws://127.0.0.1:9944'
  prices_path: 'prices.csv'
contracts:
  evm:
    additional_params: "factory/additional_config.json"
    proxy: "contracts/GatewayProxy.sol/GatewayProxy.json"
    gateway: "contracts/Gateway.sol/Gateway.json"
    tester: "contracts/GmpProxy.sol/GmpProxy.json"
networks:
  13:
    backend: "evm"
    blockchain: "arbitrum"
    network: "sepolia"
    url: "wss://arbitrum-sepolia-rpc.publicnode.com"
    gateway_funds: 0
    chronicle_funds: 0
    batch_size: 512
    batch_offset: 0
    batch_gas_limit: 500000000000000
    gmp_margin: 0.0
    shard_task_limit: 100
    route_gas_limit: 10000000
    route_base_fee: 1400000000
    shard_size: 6
    shard_threshold: 4
chronicles: 
- http://127.0.0.1:8080
