config:
  chronicle_timechain_funds: 10.
  timechain_url: 'ws://validator:9944'
  prices_path: 'prices.csv'
contracts:
  evm:
    additional_params: "/etc/deployer/additional_config.json"
    proxy: "/etc/contracts/GatewayProxy.sol/GatewayProxy.json"
    gateway: "/etc/contracts/Gateway.sol/Gateway.json"
    tester: "/etc/contracts/GmpProxy.sol/GmpProxy.json"
networks:
  2:
    backend: "evm"
    blockchain: "ethereum"
    network: "dev"
    url: "ws://chain-2-evm:8545"
    gateway_funds: 1.
    chronicle_target_funds: .1
    batch_size: 64
    batch_offset: 0
    batch_gas_limit: 10000
    gmp_margin: 0.0
    shard_task_limit: 50
    symbol: "ETH"
    token_decimals: 18
    route_gas_limit: 10000000
    route_base_fee: 1400000000
    shard_size: 1
    shard_threshold: 1
  3:
    backend: "evm"
    blockchain: "ethereum"
    network: "dev"
    url: "ws://chain-3-evm:8545"
    gateway_funds: 1.
    chronicle_target_funds: .1
    batch_size: 64
    batch_offset: 0
    batch_gas_limit: 10000
    gmp_margin: 0.0
    shard_task_limit: 50
    symbol: "ETH"
    token_decimals: 18
    route_gas_limit: 10000000
    route_base_fee: 1400000000
    shard_size: 1
    shard_threshold: 1
chronicles: 
  - http://timechain-chronicle-2-evm-1:8080
  - http://timechain-chronicle-3-evm-1:8080
