[package]
name = "payable-task-executor"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.71"
bincode = "1.3.3"
codec = { package = "parity-scale-codec", version = "3.5.0", default-features = false, features = ["derive"] }
futures = "0.3.28"
log = "0.4.17"
rosetta-client = "0.2.5"
sc-client-api = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43" }
serde_json = "1.0.96"
sp-api = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43" }
sp-blockchain = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43" }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43" }
sp-keystore = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43" }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43" }
time-db = { path = "../database" }
time-primitives = { path = "../../primitives/time-primitives" }
tokio = "1.28.1"
