[package]
name = "runtime-common"
version = "1.0.0"
license = "LGPL-3.0"

authors.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
sp-core = { git = "https://github.com/analog-labs/polkadot-sdk", tag = "v1.13.0-patched", default-features = false }
sp-weights = { git = "https://github.com/analog-labs/polkadot-sdk", tag = "v1.13.0-patched", default-features = false }

[features]
default = [ "std" ]
std = [
	"sp-core/std",
	"sp-weights/std",
]
runtime-benchmarks = []
development = []
