[package]
name = "runtime-common"
authors = [ "Analog Devs <https://github.com/Analog-Labs>" ]
edition = "2021"
homepage = ""
license = "LGPL-3.0"
repository = ""
version = "1.0.0"
[dependencies]
sp-core = { git = "https://github.com/analog-labs/polkadot-sdk", tag = "v1.13.0-patched", default-features = false }
sp-weights = { git = "https://github.com/analog-labs/polkadot-sdk", tag = "v1.13.0-patched", default-features = false }

[features]
default = [ "std" ]
std = [
	"sp-core/std",
	"sp-weights/std",
]
runtime-benchmarks = []
fast-runtime = []
