[dependencies]
sp-core = { branch = "polkadot-v1.0.0", default-features = false, git = "https://github.com/paritytech/substrate.git" }
sp-weights = { branch = "polkadot-v1.0.0", default-features = false, git = "https://github.com/paritytech/substrate.git" }

[features]
default = [ "std" ]
runtime-benchmarks = []
std = [
	"sp-core/std",
	"sp-weights/std",
]
[package]
authors = [ "Analog Devs <https://github.com/Analog-Labs>" ]
edition = "2021"
homepage = ""
license = "LGPL-3.0"
name = "runtime-common"
repository = ""
version = "1.0.0"
