config:
  chronicle_timechain_funds: 10.
  timechain_url: 'wss://archive.integration.analog.one'
  prices_path: 'prices.csv'
contracts:
  evm:
    additional_params: "factory/additional_config.json"
    proxy: "contracts/GatewayProxy.sol/GatewayProxy.json"
    gateway: "contracts/Gateway.sol/Gateway.json"
    tester: "contracts/GmpProxy.sol/GmpProxy.json"
networks:
  10:
    backend: "evm"
    blockchain: "ethereum"
    network: "sepolia"
    url: "wss://ethereum-sepolia-rpc.publicnode.com"
    gateway_funds: 1.
    chronicle_target_funds: .1
    batch_size: 64
    batch_offset: 0
    batch_gas_limit: 10000
    gmp_margin: 0.0
    shard_task_limit: 50
    symbol: "ETH"
    token_decimals: 18
    route_gas_limit: 10000000
    route_base_fee: 1400000000
    shard_size: 3
    shard_threshold: 2
  11:
    backend: "evm"
    blockchain: "astar"
    network: "shibuya"
    url: "wss://rpc.shibuya.astar.network"
    gateway_funds: 1.
    chronicle_target_funds: .1
    batch_size: 256
    batch_offset: 0
    batch_gas_limit: 10000
    gmp_margin: 0.0
    shard_task_limit: 50
    symbol: "SBY"
    token_decimals: 18
    route_gas_limit: 10000000
    route_base_fee: 1400000000
    shard_size: 3
    shard_threshold: 2
chronicles: 
- https://chronicle-1.integration.analog.one
- https://chronicle-2.integration.analog.one
- https://chronicle-3.integration.analog.one
- https://chronicle-7.integration.analog.one
- https://chronicle-8.integration.analog.one
- https://chronicle-9.integration.analog.one
