[package]
name = "timechain-integration"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
graphql_client = "0.13.0"
reqwest = { version = "0.11.18", features = ["json"] }
tokio = { version = "1.28.1", features = ["full"] }
serde_json = "1.0.102"
serde = { version = "1.0.171", optional = true }
dotenv = "0.15.0"
openssl = { version = "0.10", features = ["vendored"] }