[package]
name = "timechain-integration"
edition = "2021"
version = "0.1.0"
[dependencies]
anyhow = "1.0.72"
dotenv = "0.15.0"
graphql_client = "0.13.0"
hex = "0.4.3"
log = "0.4.20"
reqwest = { version = "0.11.18", default-features = false, features = [ "json", "rustls-tls" ] }
serde = "1.0.183"
serde_json = "1.0.104"
time-primitives = { path = "../../primitives" }
tokio = { version = "1.31.0", features = [ "full" ] }
