[dependencies]
anyhow = "1.0.72"
dotenv = "0.15.0"
graphql_client = "0.13.0"
log = "0.4.19"
reqwest = { default-features = false, features = [ "json", "rustls-tls" ], version = "0.11.18" }
serde = "1.0.171"
serde_json = "1.0.102"
time-primitives = { path = "../../primitives" }
tokio = { features = [ "full" ], version = "1.28.1" }
[package]
edition = "2021"
name = "timechain-integration"
version = "0.1.0"
