[package]
name = "tester"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.2", features = [ "derive" ] }
log = "0.4.20"
subxt = "0.31.0"
tokio = {version = "1.32.0", features = ["macros", "rt-multi-thread"]}
