[package]
name = "tester"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
bincode = "1.3.3"
clap = { version = "4.4.2", features = [ "derive" ] }
hex = "0.4.3"
num-bigint = "0.4"
ethers-solc = "2.0.1"
rosetta-client = { git = "https://github.com/analog-labs/chain-connectors", branch = "release-v0.5.0" }
surf = { version = "2.3.2", default-features = false, features = [ "h1-client-rustls" ] }
tc-subxt = { path = "../tc-subxt"}
time-primitives = { path = "../primitives" }
tokio = {version = "1.32.0", features = ["macros", "rt-multi-thread"]}
sha3 = "0.10.8"
