[package]
name = "tester"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy-primitives = { version = "0.5" }
alloy-sol-types = { version = "0.5" }
anyhow = "1.0.75"
clap = { version = "4.4.2", features = [ "derive" ] }
ethers-solc = "2.0.1"
hex = "0.4.3"
rosetta-client = { git = "https://github.com/analog-labs/chain-connectors", branch = "release-v0.5.0" }
sha3 = "0.10.8"
surf = { version = "2.3.2", default-features = false, features = [ "h1-client-rustls" ] }
tc-subxt = { path = "../tc-subxt"}
tokio = {version = "1.32.0", features = ["macros", "rt-multi-thread"]}
