[package]
name = "tc-subxt"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
async-stream = "0.3.5"
async-trait = "0.1.73"
futures = "0.3.30"
subxt = "0.32.0"
subxt-signer = { version = "0.32.0", features = ["subxt"]}
time-primitives = { path = "../primitives" }
tokio = "1.35.1"
tracing = "0.1.40"
