[package]
name = "tc-subxt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
time-primitives = { path = "../primitives" }
rosetta-server = { git = "https://github.com/Analog-Labs/chain-connectors/"}
subxt = "0.32.0"
subxt-signer = { version = "0.32.0", features = ["subxt"]}
sp-core = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "master" }
