config:
  shard_size: 1
  shard_threshold: 1
  chronicle_timechain_funds: 10000
contracts:
  evm:
    proxy: "/etc/contracts/GatewayProxy.sol/GatewayProxy.json"
    gateway: "/etc/contracts/Gateway.sol/Gateway.json"
    tester: "/etc/contracts/test_contract.sol/VotingContract.json"
networks:
  0:
    backend: "rust"
    blockchain: "rust"
    network: "rust"
    url: "/etc/db"
    gateway_funds: 10000
    chronicle_target_funds: 10000
    batch_size: 5
    batch_offset: 0
    batch_gas_limit: 10000
    shard_task_limit: 50
chronicles:
- chronicle-0
