config:
  shard_size: 1
  shard_threshold: 1
  chronicle_timechain_funds: 1000000000000
  metadata_variant: testnet
  timechain_keyfile: '/etc/timechain_admin'
  timechain_url: 'ws://validator:9944'
  target_keyfile: '/etc/target_admin'
contracts:
  evm:
    proxy: "/etc/contracts/GatewayProxy.sol/GatewayProxy.json"
    gateway: "/etc/contracts/Gateway.sol/Gateway.json"
    tester: "/etc/contracts/test_contract.sol/VotingContract.json"
networks:
  0:
    backend: "grpc"
    blockchain: "rust"
    network: "0"
    url: "http://gmp-grpc-0:3000"
    gateway_funds: 10000
    chronicle_target_funds: 10000
    batch_size: 64
    batch_offset: 0
    batch_gas_limit: 10000
    gmp_margin: 0.0
    shard_task_limit: 50
    symbol: "ETH"
    token_decimals: 18
    route_gas_limit: 10000
    route_base_fee: 10000
  1:
    backend: "grpc"
    blockchain: "rust"
    network: "1"
    url: "http://gmp-grpc-1:3000"
    gateway_funds: 10000
    chronicle_target_funds: 10000
    batch_size: 64
    batch_offset: 0
    batch_gas_limit: 10000
    gmp_margin: 0.0
    shard_task_limit: 50
    symbol: "ASTR"
    token_decimals: 18
    route_gas_limit: 10000
    route_base_fee: 10000
chronicles:
- http://chronicle-0:8080
- http://chronicle-1:8080
