[package]
name = "time-db"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.71"
time-db-migration = { path = "migration" }
sea-orm = { version = "0.11.3", features = ["runtime-tokio-rustls", "sqlx-postgres", "with-time"] }
serde = { version = "1.0.171", features = ["derive"] }
