[package]
name = "eth-bridge-runtime-api"
version = "0.1.0"
edition = "2021"
authors = ['Polka Biome Ltd. <jihoon@tutanota.de>']
license = "BSD-4-Clause"
homepage = 'https://sora.org'
repository = 'https://github.com/sora-xor/sora2-network'

[dependencies]
scale-codec = { workspace = true, features = ["derive"] }
scale-info = { version = "2", default-features = false, features = ["derive"] }
polkadot-sdk = { workspace = true, features = [
	"sp-api",
	"sp-runtime",
	"sp-std",
] }

[features]
default = ["std"]
std = ["scale-codec/std", "scale-info/std", "polkadot-sdk/std"]
