[package]
name = "pallet-staking-reward-fn"
version = "4.0.0-dev"
description = "A blochain node using the proof of time consensus."
authors = ["Analog Devs <https://github.com/analog-labs>"]
homepage = "https://analog.one/"
edition = "2021"
repository = "https://github.com/analog-labs/testnet"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lib]

[dependencies]
log = { version = "0.4.17", default-features = false }
sp-arithmetic = { version = "5.0.0", default-features = false, path = "../../../primitives/arithmetic" }

[features]
default = ["std"]
std = [
	"log/std",
	"sp-arithmetic/std",
]
