[dependencies]
anyhow = "1.0.72"
async-channel = "1.9.0"
bincode = "1.3.3"
futures = "0.3.28"
log = "0.4"
sc-client-api = { branch = "polkadot-v1.0.0", git = "https://github.com/paritytech/substrate.git" }
sc-network = { branch = "polkadot-v1.0.0", git = "https://github.com/paritytech/substrate.git" }
serde = { features = [ "derive" ], version = "1.0" }
sp-api = { branch = "polkadot-v1.0.0", git = "https://github.com/paritytech/substrate.git" }
sp-runtime = { branch = "polkadot-v1.0.0", git = "https://github.com/paritytech/substrate.git" }
time-primitives = { path = "../../primitives" }
tokio = { features = [ "time" ], version = "1.29.1" }
tss = { package = "tesseract-tss", path = "../../tss" }

[dev-dependencies]
codec = { default-features = false, features = [ "derive" ], package = "parity-scale-codec", version = "3.6.3" }
sc-consensus = { branch = "polkadot-v1.0.0", git = "https://github.com/paritytech/substrate.git" }
sc-consensus-grandpa = { branch = "polkadot-v1.0.0", git = "https://github.com/paritytech/substrate.git" }
sc-keystore = { branch = "polkadot-v1.0.0", git = "https://github.com/paritytech/substrate.git" }
sc-network-test = { branch = "polkadot-v1.0.0", git = "https://github.com/paritytech/substrate.git" }
sp-tracing = { branch = "polkadot-v1.0.0", git = "https://github.com/paritytech/substrate.git" }
strum = { features = [ "derive" ], version = "0.25.0" }
substrate-test-runtime-client = { branch = "polkadot-v1.0.0", git = "https://github.com/paritytech/substrate.git" }
[package]
edition = "2021"
name = "time-worker"
version = "0.1.0"
