[package]
name = "time-worker"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.72"
async-channel = "1.9.0"
bincode = "1.3.3"
futures = "0.3.28"
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
sc-client-api = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v1.0.0" }
sc-network = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v1.0.0" }
sp-api = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v1.0.0" }
sp-runtime = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v1.0.0" }
time-primitives = { path = "../../primitives" }
tokio = { version = "1.29.1", features = ["time"] }
tss = { path = "../../tss", package = "tesseract-tss" }

[dev-dependencies]
codec = { package = "parity-scale-codec", version = "3.6.3", default-features = false, features = ["derive"] }
sc-network-test = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v1.0.0" }
sc-consensus = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v1.0.0" }
sc-consensus-grandpa = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v1.0.0" }
sc-keystore = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v1.0.0" }
sp-tracing = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v1.0.0" }
substrate-test-runtime-client = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v1.0.0" }
strum = { version = "0.25.0", features = ["derive"] }
