[package]
name = "pallet-proxy"
version = "0.1.0"
description = "A pallet for proxy operations."
authors = ["Analog Devs <https://github.com/analog-labs>"]
homepage = "https://analog.one"
edition = "2021"
license = "Unlicense"
publish = false
repository = "https://github.com/Analog-Labs/testnet"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
codec = { package = "parity-scale-codec", version = "3.5.0", default-features = false, features = ["max-encoded-len"] }
scale-info = { version = "2.7.0", default-features = false, features = ["derive"] }
serde = { version = "1.0.163", optional = true }
frame-benchmarking = { version = "4.0.0-dev", default-features = false, optional = true, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.43" }
frame-support = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "polkadot-v0.9.43" }
frame-system = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "polkadot-v0.9.43" }
sp-runtime = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "polkadot-v0.9.43" }
time-primitives = { path = "../../primitives/time-primitives", default-features = false }
sp-std = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.43" }
pallet-balances = { version = "4.0.0-dev", default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.43" }

[features]
default = ["std"]
std = [
  "frame-support/std",
  "frame-benchmarking?/std",
  "frame-system/std",
  "codec/std",
  "sp-runtime/std",
  "scale-info/std",
  "pallet-balances/std",
  "sp-std/std",
  "time-primitives/std",
]
runtime-benchmarks = ["frame-benchmarking/runtime-benchmarks", "pallet-balances/runtime-benchmarks",]
try-runtime = ["frame-support/try-runtime", "pallet-balances/try-runtime"]
