[package]
name = "task-metadata"
version = "0.0.1"
description = "A pallet for storing task(s) metadata."
authors = ["Analog Devs <https://github.com/analog-labs>"]
homepage = "https://analog.one"
edition = "2021"
license = "Unlicense"
publish = false
repository = "https://github.com/Analog-Labs/testnet"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["max-encoded-len"] }
scale-info = { version = "2.1.2", default-features = false, features = ["derive"] }
serde = { version = "1.0.136", optional = true }
log = "0.4.0"

frame-support = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "polkadot-v0.9.30" }
frame-system = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "polkadot-v0.9.30" }
sp-runtime = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "polkadot-v0.9.30" }
time-primitives = { path = "../../primitives/time-primitives", default-features = false }
sp-std = { version = "4.0.0-dev", default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.30" }

[features]
default = ["std"]
std = [
  "frame-support/std",
  "frame-system/std",
  "codec/std",
  "sp-runtime/std",
  "scale-info/std",
]
