[package]
name = "timechain-node"
authors = [ "Analog Devs <https://github.com/analog-labs>" ]
build = "build.rs"
description = "A blochain node using the proof of time consensus."
edition = "2021"
homepage = "https://analog.one/"
repository = "https://github.com/analog-labs/testnet"
version = "0.0.1"

[package.metadata.docs.rs]
targets = [ "x86_64-unknown-linux-gnu" ]
[[bin]]
name = "timechain-node"

[dependencies]
clap = { version = "4.4.2", features = [ "derive" ] }
futures = "0.3.28"
hex-literal = "0.4.1"
lazy_static = "1.4.0"
log = "0.4.20"
serde_json = "1.0"
snow = "0.9.3"
tokio = "1.32.0"

frame-system = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "master" }
pallet-im-online = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "master" }
pallet-transaction-payment = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "master" }
sc-chain-spec = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "master" }
sc-cli = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "master", default-features = false }
sc-client-api = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "master" }
sc-consensus = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "master" }
sc-consensus-babe = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "master" }
sc-consensus-grandpa = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "master" }
sc-executor = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "master" }
sc-keystore = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "master" }
sc-network = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "master" }
sc-offchain = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "master" }
sc-service = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "master", default-features = false }
sc-telemetry = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "master" }
sc-transaction-pool = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "master" }
sc-transaction-pool-api = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "master" }
sp-consensus = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "master" }
sp-consensus-babe = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "master" }
sp-consensus-grandpa = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "master" }
sp-core = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "master" }
sp-inherents = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "master" }
sp-keyring = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "master" }
sp-keystore = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "master" }
sp-runtime = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "master" }
sp-statement-store = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "master" }
sp-timestamp = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "master" }

# node 's RPCs deps
jsonrpsee = { version = "0.20.0", features = [ "server" ] }
pallet-transaction-payment-rpc = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "master" }
sc-basic-authorship = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "master" }
sc-rpc = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "master" }
sc-rpc-api = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "master" }
sp-api = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "master" }
sp-block-builder = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "master" }
sp-blockchain = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "master" }
substrate-frame-rpc-system = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "master" }
surf = { version = "2.3.2", default-features = false, features = [ "h1-client-rustls" ] }

# These dependencies are used for runtime benchmarking
frame-benchmarking = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "master" }
frame-benchmarking-cli = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "master", default-features = false }

# Local Dependencies
runtime-common = { path = "../runtime/common" }
timechain-runtime = { path = "../runtime", version = "0.0.1" }

# CLI-specific dependencies
try-runtime-cli = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "master", optional = true }

# Runtime Workers
time-primitives = { path = "../primitives", default-features = false }

#Task-Executor
async-channel = "1.9.0"
log-panics = "2.1.0"
chronicle = { path = "../chronicle" }

[build-dependencies]
substrate-build-script-utils = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "master" }

[features]
default = []
# Dependencies that are only required if runtime benchmarking should be build.
runtime-benchmarks = ["frame-benchmarking-cli/runtime-benchmarks", "frame-benchmarking/runtime-benchmarks", "timechain-runtime/runtime-benchmarks"]
# Enable features that allow the runtime to be tried and debugged. Name might be subject to change
# in the near future.
try-runtime = ["timechain-runtime/try-runtime", "try-runtime-cli"]
