[package]
name = "timechain-node"
build = "build.rs"
description = "A blockchain node using the proof of time consensus."
version = "0.6.0"
default-run = "timechain-node"

authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true

[package.metadata.wasm-pack.profile.release]
# `wasm-opt` has some problems on linux, see
# https://github.com/rustwasm/wasm-pack/issues/781 etc.
wasm-opt = false

[package.metadata.docs.rs]
targets = [ "x86_64-unknown-linux-gnu" ]

[[bin]]
name = "timechain-node"

[dependencies]
anyhow.workspace = true
async-channel.workspace = true
async-trait.workspace = true
clap.workspace = true
futures.workspace = true
log.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tracing.workspace = true

bincode = "1.3.3"
convert_case = "0.6"
hex-literal = "0.4.1"

# Node's command and service dependencies
frame-metadata-hash-extension = { git = "https://github.com/analog-labs/polkadot-sdk", tag = "v1.13.0-patched", default-features = false }
frame-system = { git = "https://github.com/analog-labs/polkadot-sdk", tag = "v1.13.0-patched" }
frame-system-rpc-runtime-api = { git = "https://github.com/analog-labs/polkadot-sdk", tag = "v1.13.0-patched" }
pallet-im-online = { git = "https://github.com/analog-labs/polkadot-sdk", tag = "v1.13.0-patched" }
pallet-transaction-payment = { git = "https://github.com/analog-labs/polkadot-sdk", tag = "v1.13.0-patched" }
sc-authority-discovery  = { git = "https://github.com/analog-labs/polkadot-sdk", tag = "v1.13.0-patched" }
sc-chain-spec = { git = "https://github.com/analog-labs/polkadot-sdk", tag = "v1.13.0-patched" }
sc-cli = { git = "https://github.com/analog-labs/polkadot-sdk", tag = "v1.13.0-patched", default-features = false }
sc-client-api = { git = "https://github.com/analog-labs/polkadot-sdk", tag = "v1.13.0-patched", default-features = false }
sc-consensus = { git = "https://github.com/analog-labs/polkadot-sdk", tag = "v1.13.0-patched" }
sc-consensus-babe = { git = "https://github.com/analog-labs/polkadot-sdk", tag = "v1.13.0-patched" }
sc-consensus-grandpa = { git = "https://github.com/analog-labs/polkadot-sdk", tag = "v1.13.0-patched" }
sc-consensus-slots = { git = "https://github.com/analog-labs/polkadot-sdk", tag = "v1.13.0-patched" }
sc-executor = { git = "https://github.com/analog-labs/polkadot-sdk", tag = "v1.13.0-patched" }
sc-network = { git = "https://github.com/analog-labs/polkadot-sdk", tag = "v1.13.0-patched" }
sc-network-sync = { git = "https://github.com/analog-labs/polkadot-sdk", tag = "v1.13.0-patched" }
sc-offchain = { git = "https://github.com/analog-labs/polkadot-sdk", tag = "v1.13.0-patched" }
sc-service = { git = "https://github.com/analog-labs/polkadot-sdk", tag = "v1.13.0-patched", default-features = false }
sc-storage-monitor = { git = "https://github.com/analog-labs/polkadot-sdk", tag = "v1.13.0-patched" }
sc-sysinfo = { git = "https://github.com/analog-labs/polkadot-sdk", tag = "v1.13.0-patched" }
sc-telemetry = { git = "https://github.com/analog-labs/polkadot-sdk", tag = "v1.13.0-patched" }
sc-transaction-pool = { git = "https://github.com/analog-labs/polkadot-sdk", tag = "v1.13.0-patched" }
sc-transaction-pool-api = { git = "https://github.com/analog-labs/polkadot-sdk", tag = "v1.13.0-patched" }
sp-authority-discovery  = { git = "https://github.com/analog-labs/polkadot-sdk", tag = "v1.13.0-patched" }
sp-consensus = { git = "https://github.com/analog-labs/polkadot-sdk", tag = "v1.13.0-patched" }
sp-consensus-babe = { git = "https://github.com/analog-labs/polkadot-sdk", tag = "v1.13.0-patched" }
sp-consensus-grandpa = { git = "https://github.com/analog-labs/polkadot-sdk", tag = "v1.13.0-patched" }
sp-core = { git = "https://github.com/analog-labs/polkadot-sdk", tag = "v1.13.0-patched" }
sp-io = { git = "https://github.com/analog-labs/polkadot-sdk", tag = "v1.13.0-patched" }
sp-inherents = { git = "https://github.com/analog-labs/polkadot-sdk", tag = "v1.13.0-patched" }
sp-keyring = { git = "https://github.com/analog-labs/polkadot-sdk", tag = "v1.13.0-patched" }
sp-keystore = { git = "https://github.com/analog-labs/polkadot-sdk", tag = "v1.13.0-patched" }
sp-runtime = { git = "https://github.com/analog-labs/polkadot-sdk", tag = "v1.13.0-patched" }
sp-timestamp = { git = "https://github.com/analog-labs/polkadot-sdk", tag = "v1.13.0-patched" }
sp-transaction-storage-proof = { git = "https://github.com/analog-labs/polkadot-sdk", tag = "v1.13.0-patched" }

# node's rpc dependencies
jsonrpsee = { version = "0.22.1", features = [ "server" ] }
pallet-transaction-payment-rpc = { git = "https://github.com/analog-labs/polkadot-sdk", tag = "v1.13.0-patched" }
sc-basic-authorship = { git = "https://github.com/analog-labs/polkadot-sdk", tag = "v1.13.0-patched" }
sc-rpc = { git = "https://github.com/analog-labs/polkadot-sdk", tag = "v1.13.0-patched" }
sc-rpc-api = { git = "https://github.com/analog-labs/polkadot-sdk", tag = "v1.13.0-patched" }
sc-rpc-spec-v2 = { git = "https://github.com/analog-labs/polkadot-sdk", tag = "v1.13.0-patched" }
sc-consensus-babe-rpc = { git = "https://github.com/analog-labs/polkadot-sdk", tag = "v1.13.0-patched" }
sc-consensus-grandpa-rpc = { git = "https://github.com/analog-labs/polkadot-sdk", tag = "v1.13.0-patched" }
sc-sync-state-rpc = { git = "https://github.com/analog-labs/polkadot-sdk", tag = "v1.13.0-patched" }
sp-api = { git = "https://github.com/analog-labs/polkadot-sdk", tag = "v1.13.0-patched" }
sp-block-builder = { git = "https://github.com/analog-labs/polkadot-sdk", tag = "v1.13.0-patched" }
sp-blockchain = { git = "https://github.com/analog-labs/polkadot-sdk", tag = "v1.13.0-patched" }
substrate-frame-rpc-system = { git = "https://github.com/analog-labs/polkadot-sdk", tag = "v1.13.0-patched" }
substrate-state-trie-migration-rpc = { git = "https://github.com/analog-labs/polkadot-sdk", tag = "v1.13.0-patched" }

# node's benchmarking dependencies
frame-benchmarking = { git = "https://github.com/analog-labs/polkadot-sdk", tag = "v1.13.0-patched", default-features = false }
frame-benchmarking-cli = { git = "https://github.com/analog-labs/polkadot-sdk", tag = "v1.13.0-patched", default-features = false }

# node's local dependencies
chronicle = { path = "../chronicle", optional = true }
time-primitives = { path = "../primitives" }
timechain-runtime = { path = "../runtime" }
tc-subxt = { path = "../tc-subxt", optional = true }

# node's additional command line interfaces
try-runtime-cli = { git = "https://github.com/paritytech/try-runtime-cli", tag = "v0.7.0", optional = true }
staging-node-inspect = { git = "https://github.com/analog-labs/polkadot-sdk", tag = "v1.13.0-patched", default-features = false }

[build-dependencies]
substrate-build-script-utils = { git = "https://github.com/analog-labs/polkadot-sdk", tag = "v1.13.0-patched" }

[features]
default = []
# Dependencies that are only required if runtime benchmarking should be build.
runtime-benchmarks = ["frame-benchmarking-cli/runtime-benchmarks", "frame-benchmarking/runtime-benchmarks", "timechain-runtime/runtime-benchmarks"]
# Enable features that allow the runtime to be tried and debugged. Name might be subject to change
# in the near future.
try-runtime = ["timechain-runtime/try-runtime", "try-runtime-cli"]
# runs chronicle with node
chronicle = ["dep:chronicle", "dep:tc-subxt"]
