[package]
name = "offchain-call"
version = "0.1.0"
edition = "2021"

[dependencies]
log = { version = "0.4", default-features = false, features = ["std"] }
codec = { package = "parity-scale-codec", version = "3.5.0", default-features = false }
scale-info = { version = "2.7.0", default-features = false, features = ["derive"] }
sp-application-crypto = { version = "7.0.0", default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.43" }
sp-runtime = { version = "7.0.0", default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.43" }
sp-core = { version = "7.0.0", default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.43" }
frame-system = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.43" }
timechain-runtime = { default-features = false, path = "../../runtime"}
pallet-tesseract-sig-storage = { default-features = false, path = "../../pallets/tesseract-sig-storage"}
time-primitives = { default-features = false, path = "../time-primitives"}

[features]
default = ["std"]
std = ["log/std", "codec/std", "scale-info/std", "time-primitives/std", "pallet-tesseract-sig-storage/std", "timechain-runtime/std", "sp-core/std", "frame-system/std", "sp-runtime/std"]
