[package]
name = "pallet-tasks-rpc"
authors = [ "Analog Devs <https://github.com/analog-labs>" ]
description = "Rpc methods for pallet tasks"
edition = "2021"
homepage = "https://analog.one"
license = "Unlicense"
publish = false
repository = "https://github.com/Analog-Labs/testnet"
version = "0.0.1"

[dependencies]
hex = "0.4"
sp-api = { git = "https://github.com/Analog-Labs/polkadot-sdk", branch = "timechain/full-tracing", default-features = false }
sp-runtime = { git = "https://github.com/Analog-Labs/polkadot-sdk", branch = "timechain/full-tracing", default-features = false }
sp-blockchain = { git = "https://github.com/Analog-Labs/polkadot-sdk", branch = "timechain/full-tracing", default-features = false }
jsonrpsee = { version = "0.16.2", features = ["server", "macros"] } 
time-primitives = {path = "../../../primitives", default-features=false}
thiserror = "1.0.50"

[features]
default = ["std"]
std = [
  "sp-api/std"
]
