[package]
name = "pallet-elections"
authors = [ "Analog Devs <https://github.com/analog-labs>" ]
description = "A pallet for selecting members for shards."
edition = "2021"
homepage = "https://analog.one"
license = "Unlicense"
publish = false
repository = "https://github.com/Analog-Labs/testnet"
version = "0.0.1"

[package.metadata.docs.rs]
targets = [ "x86_64-unknown-linux-gnu" ]
[dependencies]
codec = { package = "parity-scale-codec", version = "3.6.4", default-features = false, features = [
	"derive",
] }
frame-benchmarking = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.0.1", default-features = false, optional = true }
frame-support = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.0.1", default-features = false }
frame-system = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.0.1", default-features = false }
log = { version = "0.4.20", default-features = false }
scale-info = { version = "2.9.0", default-features = false, features = [ "derive" ] }
sp-core = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.0.1", default-features = false, optional = true }
sp-runtime = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.0.1", default-features = false }
sp-std = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.0.1", default-features = false }
time-primitives = { path = "../../primitives", default-features = false }

[dev-dependencies]
env_logger = "0.10.0"
lazy_static = "1.4.0"
pallet-balances = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.0.1", version = "4.0.0-dev" }
sp-io = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.0.1", default-features = false }
sp-keystore = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.0.1", default-features = false }
pallet-shards = { path = "../shards" }

[features]
default = [ "std" ]
std = [ "codec/std", "frame-benchmarking?/std", "frame-support/std", "frame-system/std", "scale-info/std", "sp-core/std", "sp-runtime/std", "sp-std/std", "time-primitives/std" ]
runtime-benchmarks = [ "frame-benchmarking/runtime-benchmarks", "sp-core" ]
try-runtime = [ "frame-support/try-runtime" ]