[package]
name = "pallet-staking-reward-curve"
version = "4.0.0-dev"
description = "A blochain node using the proof of time consensus."
authors = ["Analog Devs <https://github.com/analog-labs>"]
homepage = "https://analog.one/"
edition = "2021"
repository = "https://github.com/analog-labs/testnet"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lib]
proc-macro = true

[dependencies]
proc-macro-crate = "1.1.3"
proc-macro2 = "1.0.37"
quote = "1.0.10"
syn = { version = "1.0.98", features = ["full", "visit"] }

[dev-dependencies]
#sp-runtime = { version = "6.0.0", path = "../../../primitives/runtime" }
sp-runtime = { version = "6.0.0", git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.30" }
