[package]
name = "pallet-timegraph"
version = "0.0.1"
description = "A pallet for economics of timegraph."
authors = ["Analog Devs <https://github.com/analog-labs>"]
homepage = "https://analog.one"
edition = "2021"
license = "Unlicense"
publish = false
repository = "https://github.com/Analog-Labs/testnet"

[dependencies]
codec = { package = "parity-scale-codec", version = "3.5.0", default-features = false, features = ["max-encoded-len"] }
scale-info = { version = "2.7.0", default-features = false, features = ["derive"] }
serde = { version = "1.0.163", optional = true }
frame-benchmarking = { default-features = false, optional = true, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.43" }
frame-support = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.43" }
frame-system = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.43" }
sp-runtime = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.43" }
sp-std = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.43" }


[features]
default = ["std"]
std = [
  "frame-support/std",
  "frame-benchmarking?/std",
  "frame-system/std",
  "codec/std",
  "sp-runtime/std",
  "scale-info/std",
]
runtime-benchmarks = ["frame-benchmarking/runtime-benchmarks"]
try-runtime = ["frame-support/try-runtime"]
