[package]
name = "task-executor"
version = "0.1.0"
edition = "2021"


[dependencies]
futures = "0.3.25"
futures-channel = "0.3.25"
fnv = "1.0.6"
hex = "0.4"
log = "0.4"
parking_lot = "0.11"
array-bytes = "4.1"
futures-timer = "3.0.1"
tokio = "1.24.0"
async-trait = "0.1.60"
lazy_static = "1.4"
#connector
time-worker = { path = "../time-worker"}
diesel = { version = "2.0.0", features = ["postgres"] }

codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"] }
prometheus = { package = "substrate-prometheus-endpoint", git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.30" }
frame-support = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.30" }
sp-io = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.30" }
sp-api = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.30" }
sp-application-crypto = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.30" }
sp-arithmetic = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.30" }
sp-blockchain = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.30" }
sp-consensus = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.30" }
sp-core = { features = ["full_crypto"], git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.30" }
sp-keystore = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.30" }
sp-finality-grandpa = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.30" }
sp-runtime = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.30" }
sp-inherents = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.30" }
sc-client-api = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.30" }
sc-chain-spec = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.30" }
sc-keystore = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.30" }
sc-network = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.30" }
sc-utils = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.30" }
sc-network-common = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.30" }
sc-network-gossip = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.30" }
time-primitives = { path = "../../primitives/time-primitives" }
tss = { path = "../../tesseract/tss", package = "tesseract-tss" }
accounts = { path = "../../tesseract/accounts", package = "tesseract-accounts" }
borsh = { version ="0.9", default-features = false }
web3 = "0.18.0"
[dev-dependencies]
sc-finality-grandpa = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.30" }
sc-network-test = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.30" }
sc-consensus = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.30" }
sp-tracing = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.30" }
sp-finality-grandpa = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.30" }
substrate-test-runtime-client = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.30" }
tempfile = "*"
serde = { version = "1.0", features = ["derive"] }
scale-info = "2.1.1"
strum = { version = "0.24.1", features = ["derive"] }
arrayref = "0.3.6"

[features]
expensive_tests = []