[package]
name = "task-executor"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.71"
bincode = "1.3.3"
codec = { package = "parity-scale-codec", version = "3.5.0", default-features = false, features = [
    "derive",
] }
futures = "0.3.28"
log = "0.4.17"
rosetta-client = "0.4.0"
sc-client-api = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43" }
serde_json = "1.0.96"
sp-api = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43" }
sp-blockchain = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43" }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43" }
sp-keystore = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43" }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43" }
time-db = { path = "../database" }
time-primitives = { path = "../../primitives/time-primitives" }
tokio = { version = "1.28.1", features = ["macros"] }
queue = "0.3.1"

[dev-dependencies]
sc-network-test = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.43" }
sc-keystore = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.43" }
strum = { version = "0.24.1", features = ["derive"] }
substrate-test-runtime-client = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.43" }
surf = { version = "2.3.2", features = ["h1-client-rustls"], default-features = false }
sp-std = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.43" }
ethers-solc = "2.0.1"
rosetta-docker = "0.4.1"
