[package]
name = "task-executor"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.71"
bincode = "1.3.3"
tokio = { version = "1.28.1", features = ["macros"] }
queue = "0.3.1"
codec = { package = "parity-scale-codec", version = "3.5.0", default-features = false, features = [
    "derive",
] }
dotenv = "0.15.0"
frame-support = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "polkadot-v0.9.43" }
frame-system = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "polkadot-v0.9.43" }
futures = "0.3.28"
graphql_client = "0.13.0"
reqwest = "0.11.18"
log = "0.4.17"
rosetta-client = "0.4.0"
sc-client-api = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0" }
serde_json = "1.0.102"
sp-api = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0" }
sp-blockchain = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0" }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0" }
sp-keystore = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0" }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0" }
thiserror = "1.0.43"
time-db = { path = "../database" }
time-primitives = { path = "../../primitives/time-primitives" }
timechain-integration = { path = "../timechain-integration" }

[dev-dependencies]
sc-network-test = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v1.0.0" }
sc-keystore = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v1.0.0" }
strum = { version = "0.25.0", features = ["derive"] }
substrate-test-runtime-client = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v1.0.0" }
surf = { version = "2.3.2", features = ["h1-client-rustls"], default-features = false }
sp-std = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v1.0.0" }
ethers-solc = "2.0.7"
rosetta-docker = "0.4.1"
