[dependencies]
anyhow = "1.0.71"
bincode = "1.3.3"
futures = "0.3.28"
log = "0.4.19"
rosetta-client = { git = "https://github.com/analog-labs/chain-connectors" }
sc-client-api = { branch = "polkadot-v1.0.0", git = "https://github.com/paritytech/substrate" }
serde_json = "1.0.102"
sp-api = { branch = "polkadot-v1.0.0", git = "https://github.com/paritytech/substrate" }
sp-runtime = { branch = "polkadot-v1.0.0", git = "https://github.com/paritytech/substrate" }
time-primitives = { path = "../../primitives" }
timechain-integration = { path = "../timechain-integration" }
tokio = { features = [ "macros" ], version = "1.29.1" }

[dev-dependencies]
ethers-solc = "2.0.7"
rosetta-docker = { git = "https://github.com/analog-labs/chain-connectors" }
sc-keystore = { branch = "polkadot-v1.0.0", git = "https://github.com/paritytech/substrate.git" }
sc-network-test = { branch = "polkadot-v1.0.0", git = "https://github.com/paritytech/substrate.git" }
sp-std = { branch = "polkadot-v1.0.0", default-features = false, git = "https://github.com/paritytech/substrate.git" }
strum = { features = [ "derive" ], version = "0.25.0" }
substrate-test-runtime-client = { branch = "polkadot-v1.0.0", git = "https://github.com/paritytech/substrate.git" }
surf = { default-features = false, features = [ "h1-client-rustls" ], version = "2.3.2" }
[package]
edition = "2021"
name = "task-executor"
version = "0.1.0"
