name: "Setup, cache and execute cargo command"
description: "Install dependencies, rust, cache in- and outputs and run cargo command."
inputs:
  command:
    description: 'Cargo command to run'
    required: false
    default: 'build'
  package:
    description: 'Limit execution to a specific package, assumes workspace if unset'
    required: false
  profile:
    description: 'Profile under which to run cargo command'
    required: false
    default: 'release'
  feature:
    description: 'Feature with which to run cargo command'
    required: false
  args:
    description: 'Additional argument to pass to cargo invocation'
    required: false
  cache:
    description: 'Whether to enable registry, index and compile output caching'
    required: false
    default: true
  annotate:
    description: 'Whether to provide errors as GitHub annotations'
    required: false
    default: true
runs:
  using: "composite"
  steps:
    - name: Install rust toolchain
      shell: bash
      run: rustup show
    - name: Install cargo-cache
      if: ${{ fromJSON(inputs.annotate) }}
      shell: bash
      run: cargo install cargo-action-fmt
    - name: Assemble cache key
      shell: bash
      id: cache
      run: |
        features="${{ inputs.feature }}"
        cache_key=$(echo "$features" | sed 's/,/-/g')
        echo "cache_key=$cache_key" >> $GITHUB_OUTPUT
    - name: Cache cargo registry and index
      if: ${{ fromJSON(inputs.cache) }}
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
        key: cargo-cache-${{ inputs.package || 'workspace' }}-${{ steps.cache.outputs.cache_key }}-${{ hashFiles('Cargo.lock') }}
        restore-keys: |
          cargo-cache-${{ inputs.package || 'workspace' }}-${{ steps.cache.outputs.cache_key }}-
          cargo-cache-${{ inputs.package || 'workspace' }}-default-
          cargo-cache-workspace-
    - name: Cache cargo target folder
      if: ${{ fromJSON(inputs.cache) }}
      uses: actions/cache@v4
      with:
        path: target
        key: cargo-${{ inputs.command }}-${{ inputs.profile }}-${{ inputs.package || 'workspace' }}-${{ steps.cache.outputs.cache_key }}-${{ hashFiles('Cargo.lock') }}
        restore-keys: |
          cargo-${{ inputs.command }}-${{ inputs.profile }}-${{ inputs.package || 'workspace' }}-${{ steps.cache.outputs.cache_key }}-
          cargo-${{ inputs.command }}-${{ inputs.profile }}-${{ inputs.package || 'workspace' }}-default-
          cargo-${{ inputs.command }}-${{ inputs.profile }}-workspace-
    - name: Run cargo ${{ inputs.command }}
      env:
        CARGO_TERM_COLOR: always
      shell: bash
      run: cargo ${{ inputs.command }} ${{ inputs.package && '--package' || '--workspace' }} ${{ inputs.package }} --profile '${{ inputs.profile }}' --features '${{ inputs.feature }}' ${{ fromJSON(inputs.annotate) && '--message-format json' || '' }} ${{ inputs.args }} ${{ fromJSON(inputs.annotate) && '| cargo-action-fmt' || '' }}
