[package]
name = "connector"
version = "0.1.0"
edition = "2021"

[dependencies]
web3 = "0.18.0"
tokio = {version= "1.28", features=["full"]}
log = "0.4.17"
serde_json = "1.0"
reqwest = { version = "0.11", features = ["blocking", "json"] }
