[package]
name = "connector"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
web3 = "0.18.0"
tokio = {version= "1.17", features=["full"]}
log = "0.4.0"
serde_json = "1.0.83"
reqwest = { version = "0.11", features = ["blocking", "json"] }
actix-rt = "*"
bincode = "1.3.3"