config:
  shard_size: 1
  shard_threshold: 1
  chronicle_timechain_funds: 1.
  timechain_url: 'wss://rpc.development.analog.one'
  prices_path: 'prices.csv'
contracts:
  evm:
    additional_params: "../../../gmp/evm/factory/additional_config.json"
    proxy: "../../../analog-gmp/out/GatewayProxy.sol/GatewayProxy.json"
    gateway: "../../../analog-gmp/out/Gateway.sol/Gateway.json"
    tester: "../../../analog-gmp/out/GmpProxy.sol/GmpProxy.json"
networks:
  0:
    backend: "grpc"
    blockchain: "rust"
    network: "0"
    url: "https://gmp-grpc-1.development.analog.one:443"
    gateway_funds: 10000
    chronicle_target_funds: 100000
    batch_size: 64
    batch_offset: 0
    batch_gas_limit: 10000
    shard_task_limit: 50
    route_gas_limit: 10000
    route_base_fee: 10000
    gmp_margin: 0.1
    shard_size: 3
    shard_threshold: 2

  1:
    backend: "grpc"
    blockchain: "rust"
    network: "1"
    url: "https://gmp-grpc-2.development.analog.one:443"
    gateway_funds: 10000
    chronicle_target_funds: 100000
    batch_size: 64
    batch_offset: 0
    batch_gas_limit: 10000
    shard_task_limit: 50
    route_gas_limit: 10000
    route_base_fee: 10000
    gmp_margin: 0.1
    shard_size: 3
    shard_threshold: 2

chronicles:
- https://chronicle-1.development.analog.one
- https://chronicle-2.development.analog.one
- https://chronicle-3.development.analog.one
- https://chronicle-7.development.analog.one
- https://chronicle-8.development.analog.one
- https://chronicle-9.development.analog.one
