config:
  chronicle_timechain_funds: 1.
  timechain_url: 'wss://rpc.development.analog.one'
  prices_path: 'prices.csv'
contracts:
  evm:
    additional_params: "factory/additional_config.json"
    proxy: "contracts/GatewayProxy.sol/GatewayProxy.json"
    gateway: "contracts/Gateway.sol/Gateway.json"
    tester: "contracts/GmpProxy.sol/GmpProxy.json"
networks:
  0:
    backend: "grpc"
    blockchain: "rust"
    network: "0"
    url: "https://gmp-grpc-1.development.analog.one:443"
    gateway_funds: 10.
    chronicle_target_funds: 10.
    batch_size: 64
    batch_offset: 0
    batch_gas_limit: 10000
    shard_task_limit: 50
    route_gas_limit: 10000
    route_base_fee: 10000
    gmp_margin: 0.1
    shard_size: 1
    shard_threshold: 1

  1:
    backend: "grpc"
    blockchain: "rust"
    network: "1"
    url: "https://gmp-grpc-2.development.analog.one:443"
    gateway_funds: 10.
    chronicle_target_funds: 10.
    batch_size: 64
    batch_offset: 0
    batch_gas_limit: 10000
    shard_task_limit: 50
    route_gas_limit: 10000
    route_base_fee: 10000
    gmp_margin: 0.1
    shard_size: 1
    shard_threshold: 1

  2:
    backend: "grpc"
    blockchain: "rust"
    network: "0"
    url: "https://gmp-grpc-3.development.analog.one:443"
    gateway_funds: 10.
    chronicle_target_funds: 10.
    batch_size: 64
    batch_offset: 0
    batch_gas_limit: 10000
    shard_task_limit: 50
    route_gas_limit: 10000
    route_base_fee: 10000
    gmp_margin: 0.1
    shard_size: 3
    shard_threshold: 2

  3:
    backend: "grpc"
    blockchain: "rust"
    network: "1"
    url: "https://gmp-grpc-4.development.analog.one:443"
    gateway_funds: 10.
    chronicle_target_funds: 10.
    batch_size: 64
    batch_offset: 0
    batch_gas_limit: 10000
    shard_task_limit: 50
    route_gas_limit: 10000
    route_base_fee: 10000
    gmp_margin: 0.1
    shard_size: 3
    shard_threshold: 2

  4:
    backend: "evm"
    blockchain: "ethereum"
    network: "sepolia"
    url: "wss://ethereum-sepolia-rpc.publicnode.com"
    gateway_funds: 1.
    chronicle_target_funds: .1
    batch_size: 64
    batch_offset: 0
    batch_gas_limit: 10000
    gmp_margin: 0.0
    shard_task_limit: 50
    route_gas_limit: 10000000
    route_base_fee: 1400000000
    shard_size: 1
    shard_threshold: 1

  5:
    backend: "evm"
    blockchain: "astar"
    network: "shibuya"
    url: "wss://rpc.shibuya.astar.network"
    gateway_funds: 1.
    chronicle_target_funds: .1
    batch_size: 256
    batch_offset: 0
    batch_gas_limit: 10000
    gmp_margin: 0.0
    shard_task_limit: 50
    route_gas_limit: 10000000
    route_base_fee: 1400000000
    shard_size: 1
    shard_threshold: 1

chronicles:
- https://chronicle-1.development.analog.one
- https://chronicle-2.development.analog.one
- https://chronicle-3.development.analog.one
- https://chronicle-4.development.analog.one
- https://chronicle-5.development.analog.one
- https://chronicle-6.development.analog.one
- https://chronicle-7.development.analog.one
- https://chronicle-8.development.analog.one
- https://chronicle-9.development.analog.one
- https://chronicle-10.development.analog.one
- https://chronicle-11.development.analog.one
- https://chronicle-12.development.analog.one
