config:
  shard_size: 1
  shard_threshold: 1
  chronicle_timechain_funds: 1000000000000
  metadata_variant: testnet
  timechain_url: 'wss://rpc.development-gmpv2.analog.one'
contracts:
  evm:
    proxy: "../../../analog-gmp/out/GatewayProxy.sol/GatewayProxy.json"
    gateway: "../../../analog-gmp/out/Gateway.sol/Gateway.json"
    tester: "../../../analog-gmp/out/test_contract.sol/VotingContract.json"
networks:
  0:
    backend: "grpc"
    blockchain: "rust"
    network: "0"
    url: "https://gmp-grpc-1.development-gmpv2.analog.one:443"
    gateway_funds: 10000
    chronicle_target_funds: 100000
    batch_size: 64
    batch_offset: 0
    batch_gas_limit: 10000
    shard_task_limit: 50
    route_gas_limit: 10000
    route_base_fee: 10000
    route_gas_price:
      num: 10
      den: 1
  1:
    backend: "grpc"
    blockchain: "rust"
    network: "1"
    url: "https://gmp-grpc-2.development-gmpv2.analog.one:443"
    gateway_funds: 10000
    chronicle_target_funds: 100000
    batch_size: 64
    batch_offset: 0
    batch_gas_limit: 10000
    shard_task_limit: 50
    route_gas_limit: 10000
    route_base_fee: 10000
    route_gas_price:
      num: 10
      den: 1
chronicles:
- https://chronicle-1.development-gmpv2.analog.one
- https://chronicle-2.development-gmpv2.analog.one
- https://chronicle-3.development-gmpv2.analog.one
- https://chronicle-7.development-gmpv2.analog.one
- https://chronicle-8.development-gmpv2.analog.one
- https://chronicle-9.development-gmpv2.analog.one
