[package]
name = "tesseract-accounts"
version = "0.0.1"
authors = ["Dev <Dev@analog.one>"]
edition = "2021"
license = "Apache-2.0"
homepage = "https://www.analog.one/"
repository = "https://github.com/Analog-Labs/tesseract/"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.81"
log = "0.4.0"
sp-core = { version = "7.0.0", git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.38" }
sc-keystore = { version = "4.0.0-dev", git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.38" }
sc-service = { version = "0.10.0-dev", git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.38" }
sp-keystore = { version = "0.13.0", git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.38" }
keystore = { version = "0.1.0", git = "https://github.com/Analog-Labs/Keystore.git"}
