[package]
name = "timechain-generate-bags"
version = "0.1.0"

authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
clap.workspace = true 

timechain-runtime = { path = "../../runtime" }
generate-bags = { git = "https://github.com/analog-labs/polkadot-sdk", tag = "v1.13.0-patched" }
