[package]
name = "timechain-generate-bags"
version = "0.1.0"
edition = "2021"

[dependencies]
timechain-runtime = { path = "../../runtime" }
generate-bags = { git = "https://github.com/analog-labs/polkadot-sdk", tag = "v1.13.0-patched" }

clap = { version = "4.4.18", features = [ "derive" ] }
