[package]
name = "timechain-generate-bags"
version = "0.1.0"

authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
clap.workspace = true

polkadot-sdk = { workspace = true, features = [ "generate-bags" ] }

timechain-runtime.workspace = true
