[package]
name = "testnet-runtime"
description = "Official Analog Timechain Testnet Runtime"
build = "build.rs"
publish = false

version.workspace = true
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true

[package.metadata.docs.rs]
targets = [ "x86_64-unknown-linux-gnu" ]

[dependencies]
log.workspace = true

scale-codec = { workspace = true, features = [ "max-encoded-len" ] }
scale-info.workspace = true

static_assertions = "1.1.0"

polkadot-sdk = { workspace = true, features = [
	"frame-election-provider-support",
	"frame-executive",
	"frame-metadata-hash-extension",
	"frame-support",
	"frame-system",

	"pallet-authorship",
	"pallet-authority-discovery",
	"pallet-babe",
	"pallet-bags-list",
	"pallet-balances",
	"pallet-collective",
	"pallet-election-provider-multi-phase",
	"pallet-grandpa",
	"pallet-im-online",
	"pallet-multisig",
	"pallet-offences",
	"pallet-proxy",
	"pallet-session",
	"pallet-staking",
	"pallet-staking-reward-fn",
	"pallet-sudo",
	"pallet-timestamp",
	"pallet-transaction-payment",
	"pallet-treasury",
	"pallet-utility",

	"sp-api",
	"sp-arithmetic",
	"sp-authority-discovery",
	"sp-application-crypto",
	"sp-block-builder",
	"sp-consensus-babe",
	"sp-core",
	"sp-genesis-builder",
	"sp-inherents",
	"sp-io",
	"sp-npos-elections",
	"sp-offchain",
	"sp-runtime",
	"sp-session",
	"sp-std",
	"sp-transaction-pool",
	"sp-version",
	"sp-staking",

	"frame-system-rpc-runtime-api",
	"pallet-transaction-payment-rpc-runtime-api",
]}

# Local Dependencies
pallet-dmail.workspace = true
pallet-elections.workspace = true
pallet-members.workspace = true
pallet-networks.workspace = true
pallet-shards.workspace = true
pallet-tasks.workspace = true
pallet-timegraph.workspace = true

# shared code between runtimes and/or node
runtime-common.workspace = true
time-primitives.workspace = true

[dev-dependencies]
separator = "0.4.1"

[build-dependencies]
substrate-wasm-builder = { workspace = true, optional = true }

[features]
default = [ "std" ]
std = [
	"log/std",
	"scale-codec/std",
	"polkadot-sdk/std",

	"pallet-elections/std",
	"pallet-members/std",
	"pallet-networks/std",
	"pallet-dmail/std",
	"pallet-shards/std",
	"pallet-tasks/std",
	"pallet-timegraph/std",

	"runtime-common/std",
	"time-primitives/std",

	"substrate-wasm-builder",
]
runtime-benchmarks = [
	"polkadot-sdk/frame-system-benchmarking",
	"polkadot-sdk/runtime-benchmarks",
	"polkadot-sdk/pallet-election-provider-support-benchmarking",
	"polkadot-sdk/pallet-offences-benchmarking",
	"polkadot-sdk/pallet-session-benchmarking",

	"pallet-elections/runtime-benchmarks",
	"pallet-members/runtime-benchmarks",
	"pallet-networks/runtime-benchmarks",
	"pallet-dmail/runtime-benchmarks",
	"pallet-shards/runtime-benchmarks",
	"pallet-tasks/runtime-benchmarks",
	"pallet-timegraph/runtime-benchmarks",

	"runtime-common/runtime-benchmarks",
]
try-runtime = [
	"polkadot-sdk/frame-try-runtime",
	"polkadot-sdk/try-runtime",

	"pallet-elections/try-runtime",
	"pallet-members/try-runtime",
	"pallet-networks/try-runtime",
	"pallet-dmail/try-runtime",
	"pallet-shards/try-runtime",
	"pallet-tasks/try-runtime",
	"pallet-timegraph/try-runtime",
]
development = [
	"runtime-common/development"
]
