[package]
name = "tc-subxt-metadata"
version = "0.1.0"
edition = "2021"

[dependencies]
mainnet-runtime.workspace = true
subxt = { version = "0.37.0", features = ["unstable-reconnecting-rpc-client"] }
testnet-runtime.workspace = true
time-primitives = { workspace = true, default-features = true }
