[package]
name = "tc-subxt-metadata"
version = "0.1.0"
edition = "2021"

[dependencies]
time-primitives = { workspace = true, default-features = true }
timechain-runtime = { workspace = true }

subxt = { version = "0.37.0", features = ["unstable-reconnecting-rpc-client"] }
