[package]
name = "tc-subxt-metadata"
version = "0.1.0"
edition = "2021"

[dependencies]
subxt.workspace = true

time-primitives = { workspace = true, default-features = true }

# Not used directly, but build runtime and to generate metadata
timechain-runtime.workspace = true

[features]
testnet = [
  "time-primitives/testnet",
  "timechain-runtime/testnet",
]
develop = [
  "testnet",
  "time-primitives/develop",
  "timechain-runtime/develop",
]
bridge-demo = [
  "develop",
  "timechain-runtime/bridge-demo",
]
