name: Compile tester

on:
  pull_request:
    paths-ignore:
    - 'chronicle/**'
    - 'docker/**'
    - 'docs/**'
    - 'infra/**'
    - 'js/**'
    - 'lib/**'
    - 'scripts/**'
    - 'utils/**'
    - '**/*.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-tester:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        profile:
        - production
        - testnet
    steps:
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y musl-tools protobuf-compiler
    - name: Checkout sources
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Install rust toolchain
      run : rustup show
    - name: Setup and cache sccache
      uses: visvirial/sccache-action@v1.0.1
      with:
        cache-key: sccache-tester-${{ matrix.profile }}
    - name: Cache cargo registry and index
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
        key: cargo-cache-tester-${{ hashFiles('Cargo.lock') }}
        restore-keys: cargo-cache-tester-
    - name: Cache cargo build output
      uses: actions/cache@v4
      with:
        path: target
        key: cargo-build-tester-${{ matrix.profile }}-${{ hashFiles('Cargo.lock') }}
        restore-keys: cargo-build-tester-${{ matrix.profile }}-
    - name: Build tester
      run: cargo build --package tester --profile ${{ matrix.profile }}
    - name: Upload tester
      uses: actions/upload-artifact@v4
      with:
        name: tester.${{ matrix.profile }}
        if-no-files-found: error
        path: target/${{ matrix.profile }}/tester
