name: Generate docs

on:
  pull_request:
    paths-ignore:
    - 'docker/**'
    - 'infra/**'
    - 'js/**'
    - 'scripts/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
    - name: Initialize Rust
      uses: ./.github/actions/rust-init
    - name: Checkout sources
      uses: actions/checkout@v4
    - name: Build docs
      run: cargo doc --no-deps --document-private-items --workspace
    - name: Upload docs
      uses: actions/upload-artifact@v4
      with:
        name: docs
        if-no-files-found: error
        path: target/doc
