name: Compile timechain components

on:
  pull_request:
    paths-ignore:
    - 'chronicle/**'
    - 'contracts/**'
    - 'docker/**'
    - 'docs/**'
    - 'infra/**'
    - 'js/**'
    - 'lib/**'
    - 'scripts/**'
    - 'tc-subxt/**'
    - 'tester/**'
    - 'tss/**'
    - 'utils/**'
    - '**/*.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-timechain:
    runs-on: [self-hosted-timechain]
    strategy:
      fail-fast: false
      matrix:
        include:
        - profile: testnet
          features: default
        - profile: testnet
          features: development
        - profile: testnet
          features: runtime-benchmarks
        - profile: testnet
          features: try-runtime
    steps:
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y musl-tools protobuf-compiler
    - name: Checkout sources
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        submodules: recursive
    - name: Install rust toolchain
      run : rustup show
    - name: Setup and cache sccache
      uses: visvirial/sccache-action@v1.0.1
      with:
        cache-key: sccache-timechain-${{ matrix.profile }}
    - name: Cache cargo registry and index
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
        key: cargo-cache-timechain-${{ hashFiles('Cargo.lock') }}
        restore-keys: cargo-cache-timechain-
    - name: Cache cargo build output
      uses: actions/cache@v3
      with:
        path: target
        key: cargo-build-timechain-${{ matrix.profile }}-${{ hashFiles('Cargo.lock') }}
        restore-keys: cargo-build-timechain-${{ matrix.profile }}-
    - name: Build timechain node and runtime
      uses: actions-rs/cargo@v1
      with:
        command: build 
        args: -p timechain-node --profile ${{ matrix.profile }} --features ${{ matrix.features }}
    - name: Upload timechain node
      uses: actions/upload-artifact@v4
      with:
        name: node_${{ matrix.profile }}_${{ matrix.features }}
        path: target/${{ matrix.profile }}/timechain-node
    - name: Upload timechain runtime
      uses: actions/upload-artifact@v4
      with:
        name: runtime_${{ matrix.profile }}_${{ matrix.features }}
        path: target/${{ matrix.profile }}/wbuild/timechain-runtime/timechain_runtime.compact.compressed.wasm
    - name: Upload timechain metadata
      uses: actions/upload-artifact@v4
      with:
        name: metadata_${{ matrix.profile }}_${{ matrix.features }}
        path: target/${{ matrix.profile }}/wbuild/timechain-runtime/timechain_runtime.metadata.scale

  update-metadata:
    runs-on: [self-hosted-timechain]
    needs: [ build-timechain ]
    if: ${{ always() }}
    continue-on-error: true
    steps:
    - name: Checkout pull request
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.base.ref }}
    - name: Download and update Testnet Metadata
      uses: actions/download-artifact@v4
      with:
        name: metadata_testnet_default
    - name: Download and Testnet Metadata
      run: mv timechain_runtime.metadata.scale config/subxt/testnet.default.scale
    - name: Download Development Metadata
      uses: actions/download-artifact@v4
      with:
        name: metadata_testnet_development
    - name: Update Development Metadata
      run: mv timechain_runtime.metadata.scale config/subxt/testnet.development.scale
    - name: Commit any changes to the metadata 
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        if ! git diff --quiet; then
          git config user.email "github@analog.one"
          git config user.name "Metadata Update Bot"
          git commit -am "tc-subxt: Automated metadata update"
          git push
        fi

