name: Check Set-Up & Build

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  check:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
      - name: Remove old files
        run: |
          cd /home/ubuntu/actions-runner/_work/testnet/testnet
          sudo rm -rf *
          
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Set-Up
        run: sudo apt install -y git clang curl libssl-dev llvm libudev-dev

      - name: Install Rustup
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          source $HOME/.cargo/env
          rustup default stable
          rustup update nightly
          rustup update stable
          rustup target add wasm32-unknown-unknown --toolchain nightly
      
      - name: Compiling the Build
        run : |
           cd /home/ubuntu/actions-runner/_work/testnet/testnet
           
         
    
      - name: Check Build
        run: |
          sudo docker-compose down
          sudo docker-compose up -d
          sleep 300
          docker-compose -f docker-compose-2.yml down
          docker-compose -f docker-compose-2.yml up -d
          
          
    #####
