name: Generate docs
on:
  push:
    paths-ignore:
      - 'docker/**'
      - 'infra/**'
      - 'js/**'
      - 'scripts/**'
    branches:
      - 'development'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Initialize Rust
        uses: ./.github/actions/rust-init
      - name: Build docs
        run: cargo doc --no-deps --document-private-items --workspace
      - name: Assemble structure
        env:
          DOCS_HIDEOUT: an8ohgahmoot6ro8ieReib9micau0Oow
        run: |
          mkdir target/docs
          cp -r target/doc target/docs/$DOCS_HIDEOUT
          cp docs/robots.txt target/docs/$DOCS_HIDEOUT
      - name: Deploy docs
        uses: actions/upload-pages-artifact@v3
        with:
          path: target/docs
