# tc-cli workflow
#
# HOW IT WORKS
#

name: tc-cli

on:
  workflow_dispatch:
    inputs:
      version:
        description: "tc-cli image tag (sha8 commit)"
        required: false
        type: string
      environment:
        description: "Target environment for running (K8s cluster)"
        required: true
        type: choice
        options:
          - development
          - integration
      args:
        description: "tc-cli args"
        required: true
        type: string
      thread:
        description: "Slack thread id"
        required: false
        type: string
      user:
        description: "Slack user"
        required: false
        type: string

env:
  TC_CLI_IMAGE: analoglabs/tc-cli
  REGION: us-east1

jobs:
  tc-cli:
    name: 'Run /tc-cli tag=${{ github.event.inputs.version }} ${{ github.event.inputs.args }} on ${{ github.event.inputs.environment}} #${{ github.event.inputs.thread }} @${{ github.event.inputs.user }}'
    runs-on: ubuntu-latest
    # NOTE: Dockerfile for this container is located in the infrastructure repo
    container:
      image: analoglabs/gcloud-kubectl:latest
    environment: ${{ github.event.inputs.environment }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: GKE Login
      run: |
        echo '${{ secrets.GCP_SA_KEY }}' > ${HOME}/gcp-key.json
        gcloud auth activate-service-account --key-file=${HOME}/gcp-key.json
        gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
        gcloud container clusters get-credentials ${{ github.event.inputs.environment }} --region $REGION

    - name: Run tc-cli
      id: run
      run: |
        TAG=${{ github.event.inputs.version || 'latest' }}
        IMAGE="$TC_CLI_IMAGE:${TAG:0:8}"
        NAMESPACE="timechain"
        NAME=tc-cli-${{ github.event.inputs.thread }}
        NAME=${NAME//./-}
        kubectl -n $NAMESPACE run $NAME --image=$IMAGE --attach --rm --restart=Never \
          --env="TIMECHAIN_MNEMONIC=${{ secrets.TIMECHAIN_MNEMONIC }}" \
          --env="TARGET_MNEMONIC=${{ secrets.TARGET_MNEMONIC }}" \
          --env="TOKEN_PRICE_URL=${{ secrets.TOKEN_PRICE_URL }}" \
          --env="TOKEN_API_KEY=${{ secrets.TOKEN_API_KEY }}" \
          --env="LOKI_URL=${{ secrets.LOKI_URL }}" \
          --env="LOKI_USERNAME=${{ secrets.LOKI_USERNAME }}" \
          --env="LOKI_PASSWORD=${{ secrets.LOKI_PASSWORD }}" \
          --env="NO_COLOR=1" \
          --env="SLACK_BOT_TOKEN=${{ secrets.SLACK_BOT_TOKEN }}" \
          --env="SLACK_CHANNEL_ID=${{ secrets.SLACK_CHANNEL_ID }}" \
          --env="SLACK_THREAD_TS=${{ github.event.inputs.thread }}" \
          -- --env /etc/envs/${{ github.event.inputs.environment }} ${{ github.event.inputs.args}}
