#####
#
#  when PR is updated by pushing changes to the branch
#     CI skips all jobs for Drafted PRs by default
#     CI skips all jobs for PRs labeled with `!ci-skip`
#
#  Labels:
#    !ci-draft   - runs CI for drafted PR
#    !ci-codecov - runs Code Coverage job on every PR update
#    !ci-audit   - runs Cargo Audit job on every PR update
#    !ci-integration - runs Integration Tests on every PR updates
#    !ci-skip    - skips All jobs
#

name: Main
on:
  push:
    # add your default branch if is not there
    # however you really want to run CI on that branch
    # do not forget set env.RUNALL_ONPUSH to true
    branches: [ trying, staging ]
  pull_request:
    types: [ synchronize, opened, ready_for_review, labeled, unlabeled ]
    paths-ignore:
      - '**/*.md' # do not run CI on pull_request update if just MD files are changed

concurrency:
  # do not run more than once for latest push/update
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write
  statuses: write
  checks: write

env:
  CARGO_INCREMENTAL: 0
  CARGO_TERM_COLOR: always
  #CARGO_LOG: cargo::core::compiler::fingerprint=trace
  GLOBAL_CARGO_OPTS:

  # set to true only if you need run all test
  # for the target branch
  # It's not really necessary, since bors is used for merge
  RUNALL_ONPUSH: false

  # add package names to exclude unit tests
  EXCLUDE_TESTS:

  # clippy opts
  # `-D warnings` considers any warning as an error
  # `-W clippy::all` considers all messages as warning
  CLIPPY_OPTS: -W clippy::all

  # build configuration
  RELEASE: true

jobs:
  # it calculates conditions to run following jobs
  conditions:
    name: Conditions
    if: ${{
      ( github.event_name != 'pull_request' ||
        ( github.event.action != 'labeled' &&
          github.event.action != 'unlabeled' &&
          ( contains(github.event.pull_request.labels.*.name,'!ci-draft') ||
            github.event.pull_request.draft == false )) ||
          ( github.event.action == 'labeled' &&
            ( github.event.label.name == '!ci-draft' ||
              contains(github.event.pull_request.labels.*.name,'!ci-draft') ||
            github.event.pull_request.draft == false ) &&
          ( github.event.label.name == '!ci-codecov' ||
            github.event.label.name == '!ci-audit'||
            github.event.label.name == '!ci-integration' ||
            github.event.label.name == '!ci-draft' ) )  ||
        ( github.event.action == 'unlabeled' && github.event.label.name == '!ci-skip' )) && 
      ( !contains(github.event.pull_request.labels.*.name,'!ci-skip') ||
        ( github.event.action == 'unlabeled' && github.event.label.name == '!ci-skip' ))
      }}
    runs-on: ubuntu-latest
    steps:
      - run: true
    outputs:
      # it's push into staging/tying by bors
      staging-ci: ${{ github.ref == 'refs/heads/trying' || github.ref == 'refs/heads/staging' }}

      # it's non-draft pull_request
      general-ci: ${{
        github.event_name == 'pull_request' ||
        github.ref == 'refs/heads/trying' ||
        github.ref == 'refs/heads/staging' ||
        env.RUNALL_ONPUSH == 'true' }}

      # it's push into development branch (by bors or conventional merge)
      # it's non-draft pull_request with label `!ci-codecov`
      codecov: ${{
        ( github.event_name == 'push' && github.ref != 'refs/heads/trying' &&
          ( github.ref == 'refs/heads/staging' || env.RUNALL_ONPUSH == 'true' ) ) ||
        ( github.event_name == 'pull_request' &&
          contains(github.event.pull_request.labels.*.name,'!ci-codecov') ) }}

      # it's push into staging/tying by bors
      # it's non-draft pull_request with label `!ci-integration`
      integration: ${{
        ( github.event_name == 'push' &&
          github.ref == 'refs/heads/trying' ||
          github.ref == 'refs/heads/staging' ||
          env.RUNALL_ONPUSH == 'true' ) ||
        ( github.event_name == 'pull_request' &&
          contains(github.event.pull_request.labels.*.name,'!ci-integration') ) }}

      audit: ${{
        ( github.event_name == 'push' &&
          github.ref == 'refs/heads/trying' ||
          github.ref == 'refs/heads/staging' ||
          env.RUNALL_ONPUSH == 'true' ) ||
        ( github.event_name == 'pull_request' &&
          contains(github.event.pull_request.labels.*.name,'!ci-audit') ) }}

      build_opts: ${{ env.RELEASE == 'true' && '--release' || '' }} ${{env.GLOBAL_CARGO_OPTS}}
      target: ${{ env.RELEASE == 'true' && 'release' || 'debug' }}

  # The Bors bot checks this job status
  ci-success:
    name: Bors-CI
    if: ${{needs.conditions.outputs.staging-ci == 'true'}}
    needs: [build-and-tests, audit, code-coverage, integration-tests]
    runs-on: ubuntu-latest
    steps:
      # a filler
      - run: false

  # It builds project and warm up cache if it does not exist yet
  cache-project:
    name: Fmt Check + Cache Project
    needs: [conditions]
    if: ${{needs.conditions.outputs.general-ci == 'true'}}
    runs-on: ubuntu-latest
    env:
      BUILD_OPTS: ${{needs.conditions.outputs.build_opts}}
      TARGET: ${{needs.conditions.outputs.target}}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Update Rust
        id: rustc-version
        shell: pwsh
        run: .github/update-rust.ps1

      - name: Cargo fmt Check
        run: cargo fmt --all -- --check

      - name: Set up cache
        uses: actions/cache@v3
        id: cache
        continue-on-error: false
        with:
          path: |
            ~/.cargo
            target/
          key: "Main-${{ runner.os }}-r${{ steps.rustc-version.outputs.value }}-${{ hashFiles('**/Cargo.lock') }}"

      - name: Install Protoc
        if: steps.cache.outputs.cache-hit != 'true'
        run: sudo apt-get install -y protobuf-compiler

      - name: Warming up the cache
        # do not run if cache exists
        #  because of it will not affect tests/clippy, just will take a time
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          cargo fetch --locked
          find ~/.cargo -type d -name ".git" -exec rm -f '{}/objects/pack/*.pack' \;
          cargo test --no-run --lib --workspace --locked $BUILD_OPTS \
            $(for i in $EXCLUDE_TESTS; do echo "--exclude $i"; done )
          cargo build --locked $BUILD_OPTS

      - name: Clean up cache
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          find target/$TARGET -type f ! \( -name "*.so.*" -o -name "*.so" \) -executable -delete
          find target/$TARGET -maxdepth 1 -type f -delete
          rm -rf target/$TARGET/examples
          rm -rf target/$TARGET/wbuild/*/target
          rm -rf target/$TARGET/build/librocksdb-sys-*/out/rocksdb          
    outputs:
      cache-hit: ${{ steps.cache.outputs.cache-hit }}

  # it runs tests
  build-and-tests:
    name: Build + Clippy + Tests
    needs: [conditions,cache-project]
    runs-on: ubuntu-latest
    env:
      BUILD_OPTS: ${{needs.conditions.outputs.build_opts}}
      TARGET: ${{needs.conditions.outputs.target}}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Install Protoc
        run: sudo apt-get install -y protobuf-compiler
      - name: Update Rust
        id: rustc-version
        shell: pwsh
        run: .github/update-rust.ps1

      - name: Set up cache
        uses: actions/cache@v3
        id: cache
        continue-on-error: false
        with:
          path: |
            ~/.cargo
            target/
          key: "Main-${{ runner.os }}-r${{steps.rustc-version.outputs.value}}-${{ hashFiles('**/Cargo.lock') }}"

      - name: Check cache hit status
        if: steps.cache.outputs.cache-hit != 'true'
        # fail build
        run: |
          false

      - name: Check that the application builds successfully
        run: |
          cargo build --locked $BUILD_OPTS

      - name: Run Unit tests
        run: |
          cargo test --lib --workspace --locked $BUILD_OPTS \
            $(for i in $EXCLUDE_TESTS; do echo "--exclude $i"; done )

      - name: Run Examples
        run: |
          cargo test --examples --workspace --locked $BUILD_OPTS

      - name: Check sources with Clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          # `--no-deps` does not check dependencies out of workspace
          args: --all-targets --locked --workspace ${{env.BUILD_OPTS}} -- --no-deps ${{env.CLIPPY_OPTS}}
          name: Clippy Report

      #- name: Run Integration/Heavy Tests
      #  if: ${{ needs.conditions.outputs.integration == 'true' }}
      #  run: |
      #    cargo test --locked --test '*' --workspace $BUILD_OPTS

  # it runs integration tests (if you have one)
  integration-tests:
    if: ${{ needs.conditions.outputs.integration == 'true' }}
    needs: [conditions,cache-project]
    name: Integration Tests
    runs-on: ubuntu-latest
    env:
      BUILD_OPTS: ${{ needs.conditions.outputs.build_opts }}
      TARGET: ${{ needs.conditions.outputs.target }}
    steps:
      - uses: actions/checkout@v3
      - name: Install Protoc
        run: sudo apt-get install -y protobuf-compiler
      - name: Update Rust
        id: rustc-version
        shell: pwsh
        run: .github/update-rust.ps1

      - name: Set up cache
        id: cache
        uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            ~/.cargo
            target/
          key: "Main-${{ runner.os }}-r${{steps.rustc-version.outputs.value}}-${{ hashFiles('**/Cargo.lock') }}"

      - name: Check cache hit status
        if: steps.cache.outputs.cache-hit != 'true'
        # fail build
        run: |
          false

      - name: Run Cargo Integration/Heavy Test
        run: |
          cargo test --locked --test '*' --workspace $BUILD_OPTS

  # it does security audit for known issues with list of dependencies
  audit:
    name: Cargo Audit
    if: ${{ needs.conditions.outputs.audit == 'true' }}
    needs: [conditions]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Update Rust
        id: rustc-version
        shell: pwsh
        run: .github/update-rust.ps1

      # looks like it's better to use plane text reporter
      #  because of an error in audit check action
      #  when it used on pull-requests
      - name: Set up cache
        id: cache
        uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            ~/.cargo/bin/cargo-audit
          key: "Audit-${{ runner.os }}-r${{steps.rustc-version.outputs.value}}-${{ hashFiles('**/Cargo.lock') }}"

      - name: Warm up the cache
        if: ${{ steps.cache.outputs.cache-hit != 'true' }}
        run: |
          cargo install cargo-audit --locked 

      - name: Audit
        run: |
          $r = (cargo audit -q --json | ConvertFrom-Json)
          $e = $?
          $r.vulnerabilities.list | Select-Object -ExpandProperty Advisory
          if (!$e) { exit 1 }
        shell: pwsh

  # it measures code coverage and reports to codecov.io
  code-coverage:
    name: Report Code Coverage
    # we can need to update code coverage stats on the default branch
    if: ${{ needs.conditions.outputs.codecov == 'true' }}
    needs: [conditions]
    runs-on: ubuntu-latest
    env:
      BUILD_OPTS: ${{ needs.conditions.outputs.build_opts }}
      TARGET: ${{ needs.conditions.outputs.target }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Install Protoc
        run: sudo apt-get install -y protobuf-compiler
      - name: Update Rust
        id: rustc-version
        shell: pwsh
        run: .github/update-rust.ps1

      - name: Setup llvm-cov for cargo
        uses: taiki-e/install-action@cargo-llvm-cov

      - name: Set up cache
        id: cache
        uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            ~/.cargo
            target/
          key: "Codecov-${{ runner.os }}-r${{steps.rustc-version.outputs.value}}-${{ hashFiles('**/Cargo.lock') }}"

      - name: Warm up the cache
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          cargo fetch --locked

      - name: Unit tests should pass successfully
        # use --tests to measure coverage with all tests
        # use --test '*' to measure coverage with integration-tests
        # use --lib to measure coverage with unit-tests
        run: |
          cargo llvm-cov test --lib --locked --workspace \
            --lcov --output-path lcov.info  $BUILD_OPTS \
            $(for i in $EXCLUDE_TESTS; do echo "--exclude $i"; done )

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: lcov.info
          fail_ci_if_error: true

      - name: Clean up cache
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          find target/llvm-cov-target/$TARGET -type f ! \( -name "*.so.*" -o -name "*.so" \) -executable -delete
          find target/llvm-cov-target/$TARGET -maxdepth 1 -type f -delete
          rm -rf target/llvm-cov-target/$TARGET/examples
          rm -rf target/llvm-cov-target/$TARGET/wbuild/*/target
          rm -rf target/llvm-cov-target/$TARGET/build/librocksdb-sys-*/out/rocksdb
          find ~/.cargo -type d -name ".git" -exec rm -f '{}/objects/pack/*.pack' \;
