# Runtime WASM build & upgrade
#
# Triggers:
# 1. branch with 'ci/runtime' prefix
#    This trigger only does the srtool build without deployment.
#    The WASM blobs are attached in the build artifacts.
# 2. manual trigger (workflow_dispatch)
#    This trigger both builds and does a runtime upgrade on the selected
#    environment.
#    **NOTE**: there are no additional checks if the runtime can be applied

name: Runtime build/upgrade
on:
  workflow_dispatch:
    inputs:
      version:
        description: "tc-cli image tag (sha8 commit)"
        required: false
        type: string
      environment:
        description: "Target timechain environment"
        required: true
        type: choice
        options:
          - development
          - integration
      thread:
        description: "Slack thread id"
        required: false
        type: string
      user:
        description: "Slack user"
        required: false
        type: string
  push:
    branches:
      - "ci/runtime/**"

env:
  TC_CLI_IMAGE: analoglabs/tc-cli

jobs:

  set-tags:
    name: Get & set tags
    runs-on: ubuntu-latest
    outputs:
      commit_hash: ${{ steps.get-sha.outputs.sha }}
      commit_hash8: ${{ steps.get-sha.outputs.sha8 }}
      tc_cli: ${{ steps.check-image.outputs.image }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get SHA
        id: get-sha
        run: |
          sha=$(git log -1 --format='%H')
          echo "sha=$sha" >> $GITHUB_OUTPUT
          echo "sha8=$(git log -1 --format='%H' | cut -c1-8)" >> $GITHUB_OUTPUT
          echo "SHA commit:" $sha
      - name: Check tc-cli image
        id: check-image
        run: |
          TAG=${{ github.event.inputs.version || 'latest' }}
          IMAGE="$TC_CLI_IMAGE:${TAG:0:8}"
          echo "Checking if the image $IMAGE exists..."
          if ! docker pull "$IMAGE" &>/dev/null; then
            echo "Error: Image $IMAGE does not exist or is behind a private repo."
            exit 1
          fi
          echo "Image $IMAGE exists. Proceeding with deployment..."
          echo "IMAGE=$IMAGE" >> $GITHUB_OUTPUT

  build-runtime:
    name: Build runtimes
    needs: ["set-tags"]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          # Name denotes the artifact name in the workflow run
          - name: mainnet
            features: default
          - name: staging
            features: develop
          - name: testnet
            features: testnet
          - name: develop
            features: testnet,develop
    steps:
      - name: Fetch latest code
        uses: actions/checkout@v4
      - name: Build timechain runtime
        id: srtool_build
        uses: chevdor/srtool-actions@v0.9.2
        env:
          BUILD_OPTS: --features ${{ matrix.features }}
        with:
          image: analoglabs/srtool
          tag: 1.79.0
          chain: timechain
          runtime_dir: runtime
      - name: Srtool summary
        run: |
          echo '${{ steps.srtool_build.outputs.json }}' | jq . > timechain-srtool-digest.json
          cat timechain-srtool-digest.json
          echo "Runtime location: ${{ steps.srtool_build.outputs.wasm_compressed }}"
      - name: Upload timechain runtime artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.name }}-runtime
          if-no-files-found: error
          path: |
            ${{ steps.srtool_build.outputs.wasm_compressed }}
            timechain-srtool-digest.json
  upgrade-runtime:
    name: 'Run /runtime-upgrade tag=${{ github.event.inputs.version }} on ${{ github.event.inputs.environment }} #${{ github.event.inputs.thread }} @${{ github.event.inputs.user }}'
    # Only running when manually triggered
    if: github.event_name == 'workflow_dispatch'
    environment: ${{ github.event.inputs.environment }}
    needs: [ "build-runtime" ]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Download runtime benchmarks
      uses: actions/download-artifact@v4
      with:
        # NOTE: the assumption is that it will only deploy on development envs
        # Later we can add an input to specify what the target should be
        name: develop-runtime
    - name: Extract runtime
      run: |
        ENV="${{ github.event.inputs.environment }}"
        WASM_PATH=$(find runtime/* -type f -name "*.wasm")
        cp $WASM_PATH development-runtime.wasm

        # NOTE: environment follows folder structure
        docker run -i --rm \
          -v ./config/envs/$ENV/config.yaml:/etc/config.yaml \
          -v ./development-runtime.wasm:/etc/development-runtime.wasm \
          -e TIMECHAIN_MNEMONIC="${{ secrets.TIMECHAIN_MNEMONIC }}" \
          -e TARGET_MNEMONIC="${{ secrets.TARGET_MNEMONIC }}" \
          ${{ needs.set_tags.outputs.tc_cli }} \
          --config /etc/config.yaml runtime-upgrade /etc/development-runtime.wasm

    - name: Notify on slack
      uses: slackapi/slack-github-action@v2.0.0
      with:
        method: chat.postMessage
        token: ${{ secrets.SLACK_BOT_TOKEN }}
        payload: |
          channel: ${{ secrets.SLACK_CHANNEL_ID }}
          thread_ts: ${{ github.event.inputs.thread }}
          text: "runtime upgrade from ${{ needs.set_tags.outputs.commit_hash8 }}"
