name: Compile chronicle
on:
  pull_request:
    paths:
      - '.github/workflows/pr-build-chronicle.yaml'
      - 'chronicle/**'
      - 'config/subxt/**'
      - 'lib/**'
      - 'primitives/**'
      - 'tc-subxt/**'
      - 'tss/**'
      - 'Cargo.toml'
      - 'Cargo.lock'
      - 'rust-toolchain.toml'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build-chronicle:
    runs-on: [self-hosted, general]
    strategy:
      fail-fast: false
      matrix:
        profile:
          - production
          - testnet
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build chronicle
        uses: ./.github/actions/cargo-command
        with:
          package: chronicle
          profile: ${{ matrix.profile }}
      - name: Upload chronicle
        uses: actions/upload-artifact@v4
        with:
          name: chronicle.${{ matrix.profile }}
          if-no-files-found: error
          path: target/${{ matrix.profile }}/chronicle
