# Triggered via !ci-test-basic tag
name: Check basic integration
on:
  pull_request:
    types: [labeled, unlabeled, opened, reopened, synchronize]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  test-basic:
    runs-on: [self-hosted, general]
    if: ${{ contains(github.event.pull_request.labels.*.name,'!ci-test-basic') }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Setup containers
        run: |
          docker compose --profile ethereum up -d
      - name: Build dev containers
        run: |
          ./scripts/build_docker.sh
      - name: Setup chain
        run: |
          docker compose run tester --network '3;ws://ethereum:8545' set-shard-config 1 1
          docker compose run tester --network '3;ws://ethereum:8545' fund-wallet
      - name: Run EvmViewCall task
        timeout-minutes: 15
        run: |
          docker compose run tester --network '3;ws://ethereum:8545' --network '3;ws://ethereum:8545' test basic
      - name: Run GMP tests
        timeout-minutes: 15
        run: |
          docker compose run tester --network '3;ws://ethereum:8545' --network '3;ws://ethereum:8545' test gmp
      - name: Cleanup
        if: ${{ always() }}
        run: |
          docker compose --profile "*" down
