# Triggered via !ci-test-basic tag
name: Check basic integration
on:
  pull_request:
    types: [labeled, unlabeled, opened, reopened, synchronize]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  test-basic:
    runs-on: [self-hosted, integration]
    #if: ${{ contains(github.event.pull_request.labels.*.name,'!ci-test-basic') }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Configure sccache env for Rust
        run: | 
          echo "RUSTC_WRAPPER=sccache" >> $GITHUB_ENV
      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.5
      - name: Build dev containers
        run: |
          ./scripts/build_docker.sh
      - name: Initialize environment file
        run: |
          cat << EOF > ./config/envs/local/.env
          TIMECHAIN_MNEMONIC="${{ secrets.TIMECHAIN_MNEMONIC }}"
          TARGET_MNEMONIC="${{ secrets.TARGET_MNEMONIC }}"
          TOKEN_PRICE_URL="${{ secrets.TOKEN_PRICE_URL }}"
          TOKEN_API_KEY="${{ secrets.TOKEN_API_KEY }}"
          EOF
      - name: Setup containers
        run: |
          docker compose up -d
      - name: fetch prices
        run: |
          docker compose run --rm --remove-orphans tc-cli fetch-token-price-data
      - name: Smoke test
        run: |
          docker compose run --rm --remove-orphans tc-cli smoke-test 0 1
      - name: Cleanup
        if: ${{ always() }}
        run: |
          docker compose --profile "*" down
