# Triggered via !ci-test-basic tag
name: Check basic integration
on:
  pull_request:
    types: [labeled, unlabeled, opened, reopened, synchronize]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  test-basic:
    runs-on: [self-hosted, cache-runner]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Setup Rust cache
        uses: actions/cache@v4
        continue-on-error: false
        with:
          path: |
            ~/.cargo/
            target/            
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-
      - name: Build dev containers
        run: |
          ./scripts/build_docker.sh
      - name: Initialize environment file
        run: |
          cat << EOF > ./config/envs/local/.env
          TIMECHAIN_MNEMONIC="${{ secrets.TIMECHAIN_MNEMONIC }}"
          TARGET_MNEMONIC="${{ secrets.TARGET_MNEMONIC }}"
          TOKEN_PRICE_URL="${{ secrets.TOKEN_PRICE_URL }}"
          TOKEN_API_KEY="${{ secrets.TOKEN_API_KEY }}"
          EOF
      - name: Setup containers
        run: |
          docker compose --profile ethereum up -d
      - name: Fetch prices
        run: |
          docker compose run --rm --remove-orphans tc-cli fetch-prices
      - name: Smoke test
        run: |
          docker compose run --rm --remove-orphans tc-cli smoke-test 0 1
      - name: Restart grpc nodes
        run: |
          docker compose stop chronicle-0 chronicle-1 #gmp-grpc-0 gmp-grpc-1
          sleep 180s
          docker compose start chronicle-0 chronicle-1 #gmp-grpc-0 gmp-grpc-1
      - name: Still works
        run: |
          docker compose run --rm --remove-orphans tc-cli smoke-test 1 0
      - name: Cleanup containers
        if: ${{ always() }}
        run: |
          docker compose --profile "*" down
      - name: Cleanup working dir
        if: ${{ always() }}
        uses: eviden-actions/clean-self-hosted-runner@v1
