name: Run all except e2e tests
on:
  pull_request:
    paths:
      - '.github/actions/cargo-command/**'
      - '.github/workflows/pr-test-cargo.yaml'
      - 'chronicle/**'
      - 'config/subxt/**'
      - 'docs/**'
      - 'node/**'
      - 'pallets/**'
      - 'primitives/**'
      - 'runtime/**'
      - 'tc-cli/**'
      - 'tc-subxt/**'
      - 'tss/**'
      - 'utils/**'
      - 'Cargo.toml'
      - 'Cargo.lock'
      - 'rust-toolchain.toml'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  test-cargo:
    runs-on: [self-hosted, general]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build testsuite
        uses: ./.github/actions/cargo-command
        with:
          command: test
          args: --all-features --no-run
      - name: Run testsuite
        uses: ./.github/actions/cargo-command
        with:
          command: test
          args: --all-features --exclude timechain
          cache: false
          annotate: false
