name: Check code linter
on:
  pull_request:
    paths:
      - '.github/actions/cargo-command/**'
      - '.github/workflows/pr-test-clippy.yaml'
      - 'chronicle/**'
      - 'config/subxt/**'
      - 'docs/**'
      - 'node/**'
      - 'pallets/**'
      - 'primitives/**'
      - 'runtime/**'
      - 'tc-subxt/**'
      - 'tester/**'
      - 'tss/**'
      - 'utils/**'
      - 'Cargo.toml'
      - 'Cargo.lock'
      - 'rust-toolchain.toml'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  test-clippy:
    runs-on: [self-hosted, general]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Run clippy linter
        uses: ./.github/actions/cargo-command
        with:
          command: clippy
          features: runtime-benchmarks,try-runtime
          args: --all-targets -- -D warnings
